const ShoppingApps = [
  {
    id: '1',
    name: 'Flipkart',
    url: 'https://www.flipkart.com/',
    images: 'https://i.ibb.co/2jdQQ4J/flipkart.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a1',
  },
  {
    id: '2',
    name: 'Amazon',
    url: 'https://www.amazon.in/',
    images: 'https://i.ibb.co/bP0Jbhv/amazon.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a2',
  },
  {
    id: '3',
    name: 'Limeroad',
    url: 'https://www.limeroad.com/',
    images: 'https://i.ibb.co/PDXZZHj/limeroad.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a3',
  },
  {
    id: '4',
    name: 'Ajio',
    url: 'https://www.ajio.com/',
    images: 'https://i.ibb.co/6tqG9vx/ajio.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a4',
  },
  {
    id: '5',
    name: 'Myntra',
    url: 'https://www.myntra.com/',
    images: 'https://i.ibb.co/5FwxMp9/myntra.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a5',
  },
  {
    id: '7',
    name: 'MamaEarth',
    url: 'https://mamaearth.in/',
    images: 'https://i.ibb.co/mN4F65g/Mamaearth.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a6',
  },
  {
    id: '8',
    name: 'Paytm Mall',
    url: 'https://paytmmall.com/',
    images: 'https://i.ibb.co/GPmTTFL/paytmmall.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a7',
  },
  {
    id: '9',
    name: 'ShopClues',
    url: 'https://www.shopclues.com/',
    images: 'https://i.ibb.co/VDVQ9QS/shopclues.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a8',
  },
  {
    id: '10',
    name: 'HopScotch',
    url: 'https://www.hopscotch.in/',
    images: 'https://i.ibb.co/3yNJ3DS/hopscotch.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a9',
  },
  {
    id: '11',
    name: 'Ali Express',
    url: 'https://www.aliexpress.com/',
    images: 'https://i.ibb.co/LNBVMQf/allexpress.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a10',
  },
  {
    id: '12',
    name: 'Faballey',
    url: 'https://www.faballey.com/',
    images: 'https://i.ibb.co/nr5n12G/faballey.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a11',
  },
  {
    id: '13',
    name: 'Nyka Fashion',
    url: 'https://www.nykaafashion.com/',
    images: 'https://i.ibb.co/QmdDGCv/nykafashion.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a12',
  },
  {
    id: '14',
    name: 'Clovia',
    url: 'https://www.clovia.com/',
    images: 'https://i.ibb.co/QXMjQf5/clovia.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a13',
  },
];

const SocialApps = [
  {
    id: '1',
    name: 'Facebook',
    url: 'https://www.facebook.com/',
    images: 'https://i.ibb.co/0cbVBD2/facebook.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a14',
  },
  {
    id: '2',
    name: 'Instagram',
    url: 'https://www.instagram.com/',
    images: 'https://i.ibb.co/r4LSkhJ/instagram.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a15',
  },
  {
    id: '3',
    name: 'Twitter',
    url: 'https://twitter.com/',
    images: 'https://i.ibb.co/D7VSDqY/twitter.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a16',
  },
  {
    id: '4',
    name: 'Youtube',
    url: 'https://www.youtube.com/',
    images: 'https://i.ibb.co/wyMpKp1/youtube.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a17',
  },
  {
    id: '5',
    name: 'Linkedin',
    url: 'https://www.linkedin.com/',
    images: 'https://i.ibb.co/qW1nD6Z/linkedin.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a18',
  },
  {
    id: '6',
    name: 'Pintrest',
    url: 'https://in.pinterest.com/',
    images: 'https://i.ibb.co/D1pd1r9/pinterest-circular-logo-symbol.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a19',
  },
  {
    id: '7',
    name: 'Telegram',
    url: 'https://web.telegram.org/#/login',
    images: 'https://i.ibb.co/PhJv7Kn/telegram.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a20',
  },
  {
    id: '8',
    name: 'Tumblr',
    url: 'https://www.tumblr.com/',
    images: 'https://i.ibb.co/T8TvSyR/tumblr-logo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a21',
  },
  {
    id: '9',
    name: 'Reddit',
    url: 'https://www.reddit.com/',
    images: 'https://i.ibb.co/VSFKPMH/reddit.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a22',
  },
];

const FoodApps = [
  {
    id: '1',
    name: 'Zomato',
    url: 'https://www.zomato.com/',
    images: 'https://i.ibb.co/mSTG8L5/zomato.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a23',
  },
  {
    id: '2',
    name: 'Swiggy',
    url: 'https://www.swiggy.com/',
    images: 'https://i.ibb.co/Y8QyV8z/swiggy.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a24',
  },
  {
    id: '3',
    name: 'Food Panda',
    url: 'https://www.foodpanda.com/',
    images: 'https://i.ibb.co/jTw8stm/foodpanda-1613373-1369420.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a25',
  },
  {
    id: '4',
    name: 'Dominos',
    url: 'https://pizzaonline.dominos.co.in/',
    images: 'https://i.ibb.co/vHg4Y76/dominos.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a26',
  },
  {
    id: '6',
    name: 'Fresh Menu',
    url: 'https://www.freshmenu.com/',
    images: 'https://i.ibb.co/P9nLF22/freshmenu.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a27',
  },
  {
    id: '7',
    name: 'MacDonalds',
    url: 'https://www.mcdonaldsindia.com/',
    images: 'https://i.ibb.co/zxxJBdd/mcdonalds-icon-15.jpg',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a28',
  },
  {
    id: '8',
    name: 'KFC',
    url: 'https://online.kfc.co.in/home',
    images: 'https://i.ibb.co/yNrPdhk/kfc.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a29',
  },
];

const GroceryApps = [
  {
    id: '1',
    name: 'Amazon',
    url: 'https://www.amazon.in/pantry-online-grocery-shopping-store/',
    images: 'https://i.ibb.co/bP0Jbhv/amazon.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a30',
  },
  {
    id: '2',
    name: 'Big Basket',
    url: 'https://www.bigbasket.com/',
    images: 'https://i.ibb.co/r5twSpR/bigbasket.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a31',
  },
  {
    id: '3',
    name: 'Grofers',
    url: 'https://grofers.com/',
    images: 'https://i.ibb.co/XpXKG86/grofers-9323ba1.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a32',
  },
  {
    id: '4',
    name: 'FreshToHome',
    url: 'https://www.freshtohome.com/',
    images: 'https://i.ibb.co/34dH6JF/freshtohome.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a33',
  },
  {
    id: '5',
    name: 'EasyDayClub',
    url: 'https://www.easyday.in/',
    images: 'https://i.ibb.co/svKbmRj/easyday.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a34',
  },
  {
    id: '6',
    name: 'StarQuick',
    url: 'https://www.starquik.com/',
    images: 'https://i.ibb.co/qmpbmhP/starquick.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a35',
  },
];

const MedicalApps = [
  {
    id: '1',
    name: 'Apollo',
    url: 'https://www.apollopharmacy.in/',
    images: 'https://i.ibb.co/9scbhkg/apollo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a36',
  },
  {
    id: '2',
    name: 'Practo',
    url: 'https://www.practo.com/',
    images: 'https://i.ibb.co/HDNjm5w/practo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a37',
  },
  {
    id: '3',
    name: 'Medlife',
    url: 'https://www.medlife.com/',
    images: 'https://i.ibb.co/4R0zP52/medlife-logo-box.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a38',
  },
  {
    id: '4',
    name: 'NetMeds',
    url: 'https://www.netmeds.com/',
    images: 'https://i.ibb.co/GHckTLW/netmeds.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a39',
  },
  {
    id: '5',
    name: '1Mg',
    url: 'https://www.1mg.com/',
    images: 'https://i.ibb.co/q522Kbk/1mg-logo-large.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a40',
  },
  {
    id: '6',
    name: 'PharmEasy',
    url: 'https://pharmeasy.in/',
    images: 'https://i.ibb.co/Cw90WR2/pharmaeasy.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a41',
  },
];

const FurnitureApps = [
  {
    id: '1',
    name: 'PeperFry',
    url: 'https://www.pepperfry.com/',
    images: 'https://i.ibb.co/jVpWcLp/peperfry.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a42',
  },
  {
    id: '2',
    name: 'Flipkart',
    url: 'https://www.flipkart.com/furniture-store',
    images: 'https://i.ibb.co/2jdQQ4J/flipkart.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a43',
  },
  {
    id: '3',
    name: 'HomeTown',
    url: 'https://www.hometown.in/',
    images: 'https://i.ibb.co/bKHy8hT/hometown.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a44',
  },
  {
    id: '4',
    name: 'RentoMojo',
    url: 'https://www.rentomojo.com/',
    images: 'https://i.ibb.co/9wgdL6N/rentomozo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a45',
  },
  {
    id: '5',
    name: 'Amazon',
    url: 'https://www.amazon.in/pantry-online-grocery-shopping-store/',
    images: 'https://i.ibb.co/bP0Jbhv/amazon.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a46',
  },
  {
    id: '6',
    name: 'Furlenco',
    url: 'https://www.furlenco.com/',
    images: 'https://i.ibb.co/XtfHy2N/furlenco.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a47',
  },
];

const PopularApps = [
  {
    id: '1',
    name: 'Flipkart',
    url: 'https://www.flipkart.com/',
    images: 'https://i.ibb.co/2jdQQ4J/flipkart.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a1',
  },
  {
    id: '2',
    name: 'Amazon',
    url: 'https://www.amazon.in/',
    images: 'https://i.ibb.co/bP0Jbhv/amazon.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a2',
  },
  {
    id: '3',
    name: 'Twitter',
    url: 'https://twitter.com/',
    images: 'https://i.ibb.co/D7VSDqY/twitter.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a16',
  },
  {
    id: '4',
    name: 'Facebook',
    url: 'https://www.facebook.com/',
    images: 'https://i.ibb.co/0cbVBD2/facebook.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a14',
  },
  {
    id: '5',
    name: 'Zomato',
    url: 'https://www.zomato.com/',
    images: 'https://i.ibb.co/mSTG8L5/zomato.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a23',
  },
  {
    id: '6',
    name: 'Big Basket',
    url: 'https://www.bigbasket.com/',
    images: 'https://i.ibb.co/r5twSpR/bigbasket.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a31',
  },
  {
    id: '7',
    name: 'Apollo',
    url: 'https://www.apollopharmacy.in/',
    images: 'https://i.ibb.co/9scbhkg/apollo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a36',
  },
  {
    id: '8',
    name: '1Mg',
    url: 'https://www.1mg.com/',
    images: 'https://i.ibb.co/q522Kbk/1mg-logo-large.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a40',
  },
  {
    id: '9',
    name: 'PeperFry',
    url: 'https://www.pepperfry.com/',
    images: 'https://i.ibb.co/jVpWcLp/peperfry.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a42',
  },
  {
    id: '10',
    name: 'Furlenco',
    url: 'https://www.furlenco.com/',
    images: 'https://i.ibb.co/XtfHy2N/furlenco.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a47',
  },
];

const NewsApps = [
  {
    id: '1',
    name: 'Daily Hunt',
    url: 'https://m.dailyhunt.in/',
    images: 'https://i.ibb.co/D82bVC1/dailyhunt.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a48',
  },
  {
    id: '2',
    name: 'TOI',
    url: 'https://m.timesofindia.com/',
    images: 'https://i.ibb.co/2qCdGsr/toi.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a49',
  },
  {
    id: '3',
    name: 'NDTV',
    url: 'https://www.ndtv.com/',
    images: 'https://i.ibb.co/9yg5WQ2/ndtv.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a50',
  },
  {
    id: '4',
    name: 'Inshorts',
    url: 'https://inshorts.com/en/read',
    images: 'https://i.ibb.co/2hSHydN/inshorts.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a51',
  },
  {
    id: '5',
    name: 'Reuters',
    url: 'https://in.reuters.com/',
    images: 'https://i.ibb.co/74k0rsx/reuters.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a52',
  },
  {
    id: '6',
    name: 'EconomicTimes',
    url: 'https://economictimes.indiatimes.com/',
    images: 'https://i.ibb.co/zJwpkjn/economictimes.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a53',
  },
  {
    id: '7',
    name: 'BusinessLine',
    url: 'https://www.thehindubusinessline.com/',
    images: 'https://i.ibb.co/vdybt12/businessline.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a54',
  },
  {
    id: '8',
    name: 'Mint',
    url: 'https://www.livemint.com/',
    images: 'https://i.ibb.co/0f8JkvW/mint.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a55',
  },
  {
    id: '9',
    name: 'The Hindu',
    url: 'https://www.thehindu.com/',
    images: 'https://i.ibb.co/nRYjDY4/thehindu.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a56',
  },
  {
    id: '10',
    name: 'Express',
    url: 'https://www.financialexpress.com/',
    images: 'https://i.ibb.co/0KkcC92/financialexpress.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a57',
  },
  {
    id: '11',
    name: 'Buzz Feed',
    url: 'https://www.buzzfeed.com/in',
    images: 'https://i.ibb.co/tCPXn60/buzzfeed.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a58',
  },
  {
    id: '12',
    name: 'The Quint',
    url: 'https://www.thequint.com/',
    images: 'https://i.ibb.co/tpKR8f6/quint.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a59',
  },
];

const PayApps = [
  {
    id: '2',
    name: 'Paytm',
    url: 'https://paytm.com/',
    images: 'https://i.ibb.co/zJ7PhQ3/paytm.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a60',
  },
  {
    id: '3',
    name: 'Mobikwik',
    url: 'https://www.mobikwik.com/',
    images: 'https://i.ibb.co/ncpfTk0/mobikwik-squarelogo-1517911658186.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a61',
  },
  {
    id: '4',
    name: 'Free Charge',
    url: 'https://www.freecharge.in/',
    images: 'https://i.ibb.co/7rbbkqs/freecharge.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a62',
  },
];

const MusicApps = [
  {
    id: '1',
    name: 'Jio Savan',
    url: 'https://www.jiosaavn.com/',
    images: 'https://i.ibb.co/Rjp6WmS/saavn-icon-logo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a63',
  },
  {
    id: '2',
    name: 'Ganna',
    url: 'https://gaana.com/',
    images: 'https://i.ibb.co/mbs14Pk/ganna.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a64',
  },
  {
    id: '3',
    name: 'wynk',
    url: 'https://wynk.in/music',
    images: 'https://i.ibb.co/HHn009Z/wynk.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a65',
  },
  {
    id: '4',
    name: 'Hungama',
    url: 'https://www.hungama.com/',
    images: 'https://i.ibb.co/3hkSsfZ/hungama.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a66',
  },
];

const JobsApps = [
  {
    id: '1',
    name: 'Naukri',
    url: 'https://www.naukri.com/',
    images: 'https://i.ibb.co/DQLnQ86/naukri.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a67',
  },
  {
    id: '2',
    name: 'Indeed',
    url: 'https://in.indeed.com/',
    images: 'https://i.ibb.co/YDhYDpp/indeed.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a68',
  },
  {
    id: '3',
    name: 'Monster',
    url: 'https://www.monsterindia.com/',
    images: 'https://i.ibb.co/ZmJZ3QS/monster.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a69',
  },
  {
    id: '4',
    name: 'Glassdoor',
    url: 'https://www.glassdoor.co.in/',
    images: 'https://i.ibb.co/M6WnfxM/glasdoor.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a70',
  },
];

const ToolsApps = [
  {
    id: '1',
    name: 'Crossnote',
    url: 'https://crossnote.app/',
    images: 'https://i.ibb.co/Vw69NMY/crossnote.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a71',
  },
  {
    id: '2',
    name: 'Weather',
    url: 'https://www.accuweather.com/',
    images: 'https://i.ibb.co/d7NscmY/accuweather.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a72',
  },
  {
    id: '3',
    name: 'Multicalc',
    url: 'https://www.multicalculator.app/calculator',
    images: 'https://i.ibb.co/tb3d9jj/multicalc.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a73',
  },
  {
    id: '4',
    name: 'Todolist',
    url: 'https://todoist.com/',
    images: 'https://i.ibb.co/kgt2HxL/todo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a74',
  },
  {
    id: '5',
    name: 'Truecaller',
    url: 'https://www.truecaller.com/',
    images: 'https://i.ibb.co/RDHCnPW/truecaller.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a75',
  },
  {
    id: '6',
    name: 'LiveScore',
    url: 'https://www.cricbuzz.com/cricket-match/live-scores',
    images: 'https://i.ibb.co/fFyZPmJ/cricbuzz.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a76',
  },
  {
    id: '7',
    name: 'Horoscope',
    url: 'https://www.astrosage.com/horoscope/',
    images: 'https://i.ibb.co/F75tP54/horoscope.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a77',
  },
  {
    id: '8',
    name: 'Dictionary',
    url: ' https://www.dictionary.com/',
    images: 'https://i.ibb.co/QQ7rBmN/dictionary.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a78',
  },
  {
    id: '9',
    name: 'SpeedTest',
    url: 'https://www.speedtest.net/',
    images: 'https://i.ibb.co/df46Chb/speedtest.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a79',
  },
];

const AllApps = [
  {
    id: '1',
    name: 'Flipkart',
    url: 'https://www.flipkart.com/',
    images: 'https://i.ibb.co/2jdQQ4J/flipkart.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a1',
  },
  {
    id: '2',
    name: 'Amazon',
    url: 'https://www.amazon.in/',
    images: 'https://i.ibb.co/bP0Jbhv/amazon.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a2',
  },
  {
    id: '3',
    name: 'Limeroad',
    url: 'https://www.limeroad.com/',
    images: 'https://i.ibb.co/PDXZZHj/limeroad.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a3',
  },
  {
    id: '4',
    name: 'Ajio',
    url: 'https://www.ajio.com/',
    images: 'https://i.ibb.co/6tqG9vx/ajio.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a4',
  },
  {
    id: '5',
    name: 'Myntra',
    url: 'https://www.myntra.com/',
    images: 'https://i.ibb.co/5FwxMp9/myntra.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a5',
  },
  {
    id: '7',
    name: 'MamaEarth',
    url: 'https://mamaearth.in/',
    images: 'https://i.ibb.co/mN4F65g/Mamaearth.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a6',
  },
  {
    id: '8',
    name: 'Paytm Mall',
    url: 'https://paytmmall.com/',
    images: 'https://i.ibb.co/GPmTTFL/paytmmall.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a7',
  },
  {
    id: '9',
    name: 'ShopClues',
    url: 'https://www.shopclues.com/',
    images: 'https://i.ibb.co/VDVQ9QS/shopclues.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a8',
  },
  {
    id: '10',
    name: 'HopScotch',
    url: 'https://www.hopscotch.in/',
    images: 'https://i.ibb.co/3yNJ3DS/hopscotch.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a9',
  },
  {
    id: '11',
    name: 'Ali Express',
    url: 'https://www.aliexpress.com/',
    images: 'https://i.ibb.co/LNBVMQf/allexpress.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a10',
  },
  {
    id: '12',
    name: 'Faballey',
    url: 'https://www.faballey.com/',
    images: 'https://i.ibb.co/nr5n12G/faballey.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a11',
  },
  {
    id: '13',
    name: 'Nyka Fashion',
    url: 'https://www.nykaafashion.com/',
    images: 'https://i.ibb.co/QmdDGCv/nykafashion.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a12',
  },
  {
    id: '14',
    name: 'Clovia',
    url: 'https://www.clovia.com/',
    images: 'https://i.ibb.co/QXMjQf5/clovia.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a13',
  },
  {
    id: '15',
    name: 'Facebook',
    url: 'https://www.facebook.com/',
    images: 'https://i.ibb.co/0cbVBD2/facebook.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a14',
  },
  {
    id: '16',
    name: 'Instagram',
    url: 'https://www.instagram.com/',
    images: 'https://i.ibb.co/r4LSkhJ/instagram.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a15',
  },
  {
    id: '17',
    name: 'Twitter',
    url: 'https://twitter.com/',
    images: 'https://i.ibb.co/D7VSDqY/twitter.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a16',
  },
  {
    id: '18',
    name: 'Youtube',
    url: 'https://www.youtube.com/',
    images: 'https://i.ibb.co/wyMpKp1/youtube.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a17',
  },
  {
    id: '19',
    name: 'Linkedin',
    url: 'https://www.linkedin.com/',
    images: 'https://i.ibb.co/qW1nD6Z/linkedin.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a18',
  },
  {
    id: '20',
    name: 'Pintrest',
    url: 'https://in.pinterest.com/',
    images: 'https://i.ibb.co/D1pd1r9/pinterest-circular-logo-symbol.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a19',
  },
  {
    id: '21',
    name: 'Telegram',
    url: 'https://web.telegram.org/#/login',
    images: 'https://i.ibb.co/PhJv7Kn/telegram.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a20',
  },
  {
    id: '22',
    name: 'Tumblr',
    url: 'https://www.tumblr.com/',
    images: 'https://i.ibb.co/T8TvSyR/tumblr-logo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a21',
  },
  {
    id: '23',
    name: 'Reddit',
    url: 'https://www.reddit.com/',
    images: 'https://i.ibb.co/VSFKPMH/reddit.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a22',
  },
  {
    id: '24',
    name: 'Zomato',
    url: 'https://www.zomato.com/',
    images: 'https://i.ibb.co/mSTG8L5/zomato.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a23',
  },
  {
    id: '25',
    name: 'Swiggy',
    url: 'https://www.swiggy.com/',
    images: 'https://i.ibb.co/Y8QyV8z/swiggy.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a24',
  },
  {
    id: '26',
    name: 'Food Panda',
    url: 'https://www.foodpanda.com/',
    images: 'https://i.ibb.co/jTw8stm/foodpanda-1613373-1369420.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a25',
  },
  {
    id: '27',
    name: 'Dominos',
    url: 'https://pizzaonline.dominos.co.in/',
    images: 'https://i.ibb.co/vHg4Y76/dominos.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a26',
  },
  {
    id: '28',
    name: 'Fresh Menu',
    url: 'https://www.freshmenu.com/',
    images: 'https://i.ibb.co/P9nLF22/freshmenu.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a27',
  },
  {
    id: '29',
    name: 'MacDonalds',
    url: 'https://www.mcdonaldsindia.com/',
    images: 'https://i.ibb.co/zxxJBdd/mcdonalds-icon-15.jpg',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a28',
  },
  {
    id: '30',
    name: 'KFC',
    url: 'https://online.kfc.co.in/home',
    images: 'https://i.ibb.co/yNrPdhk/kfc.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a29',
  },
  {
    id: '31',
    name: 'Amazon',
    url: 'https://www.amazon.in/pantry-online-grocery-shopping-store/',
    images: 'https://i.ibb.co/bP0Jbhv/amazon.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a30',
  },
  {
    id: '32',
    name: 'Big Basket',
    url: 'https://www.bigbasket.com/',
    images: 'https://i.ibb.co/r5twSpR/bigbasket.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a31',
  },
  {
    id: '33',
    name: 'Grofers',
    url: 'https://grofers.com/',
    images: 'https://i.ibb.co/XpXKG86/grofers-9323ba1.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a32',
  },
  {
    id: '34',
    name: 'FreshToHome',
    url: 'https://www.freshtohome.com/',
    images: 'https://i.ibb.co/34dH6JF/freshtohome.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a33',
  },
  {
    id: '35',
    name: 'EasyDayClub',
    url: 'https://www.easyday.in/',
    images: 'https://i.ibb.co/svKbmRj/easyday.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a34',
  },
  {
    id: '36',
    name: 'StarQuick',
    url: 'https://www.starquik.com/',
    images: 'https://i.ibb.co/qmpbmhP/starquick.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a35',
  },
  {
    id: '37',
    name: 'Apollo',
    url: 'https://www.apollopharmacy.in/',
    images: 'https://i.ibb.co/9scbhkg/apollo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a36',
  },
  {
    id: '38',
    name: 'Practo',
    url: 'https://www.practo.com/',
    images: 'https://i.ibb.co/HDNjm5w/practo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a37',
  },
  {
    id: '39',
    name: 'Medlife',
    url: 'https://www.medlife.com/',
    images: 'https://i.ibb.co/4R0zP52/medlife-logo-box.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a38',
  },
  {
    id: '40',
    name: 'NetMeds',
    url: 'https://www.netmeds.com/',
    images: 'https://i.ibb.co/GHckTLW/netmeds.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a39',
  },
  {
    id: '41',
    name: '1Mg',
    url: 'https://www.1mg.com/',
    images: 'https://i.ibb.co/q522Kbk/1mg-logo-large.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a40',
  },
  {
    id: '42',
    name: 'PharmEasy',
    url: 'https://pharmeasy.in/',
    images: 'https://i.ibb.co/Cw90WR2/pharmaeasy.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a41',
  },
  {
    id: '43',
    name: 'PeperFry',
    url: 'https://www.pepperfry.com/',
    images: 'https://i.ibb.co/jVpWcLp/peperfry.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a42',
  },
  {
    id: '44',
    name: 'Flipkart',
    url: 'https://www.flipkart.com/furniture-store',
    images: 'https://i.ibb.co/2jdQQ4J/flipkart.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a43',
  },
  {
    id: '45',
    name: 'HomeTown',
    url: 'https://www.hometown.in/',
    images: 'https://i.ibb.co/bKHy8hT/hometown.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a44',
  },
  {
    id: '46',
    name: 'RentoMojo',
    url: 'https://www.rentomojo.com/',
    images: 'https://i.ibb.co/9wgdL6N/rentomozo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a45',
  },
  {
    id: '47',
    name: 'Amazon',
    url: 'https://www.amazon.in/pantry-online-grocery-shopping-store/',
    images: 'https://i.ibb.co/bP0Jbhv/amazon.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a46',
  },
  {
    id: '48',
    name: 'Furlenco',
    url: 'https://www.furlenco.com/',
    images: 'https://i.ibb.co/XtfHy2N/furlenco.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a47',
  },
  {
    id: '49',
    name: 'Daily Hunt',
    url: 'https://m.dailyhunt.in/',
    images: 'https://i.ibb.co/D82bVC1/dailyhunt.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a48',
  },
  {
    id: '50',
    name: 'TOI',
    url: 'https://m.timesofindia.com/',
    images: 'https://i.ibb.co/2qCdGsr/toi.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a49',
  },
  {
    id: '51',
    name: 'NDTV',
    url: 'https://www.ndtv.com/',
    images: 'https://i.ibb.co/9yg5WQ2/ndtv.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a50',
  },
  {
    id: '52',
    name: 'Inshorts',
    url: 'https://inshorts.com/en/read',
    images: 'https://i.ibb.co/2hSHydN/inshorts.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a51',
  },
  {
    id: '53',
    name: 'Reuters',
    url: 'https://in.reuters.com/',
    images: 'https://i.ibb.co/74k0rsx/reuters.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a52',
  },
  {
    id: '54',
    name: 'EconomicTimes',
    url: 'https://economictimes.indiatimes.com/',
    images: 'https://i.ibb.co/zJwpkjn/economictimes.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a53',
  },
  {
    id: '55',
    name: 'BusinessLine',
    url: 'https://www.thehindubusinessline.com/',
    images: 'https://i.ibb.co/vdybt12/businessline.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a54',
  },
  {
    id: '56',
    name: 'Mint',
    url: 'https://www.livemint.com/',
    images: 'https://i.ibb.co/0f8JkvW/mint.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a55',
  },
  {
    id: '57',
    name: 'The Hindu',
    url: 'https://www.thehindu.com/',
    images: 'https://i.ibb.co/nRYjDY4/thehindu.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a56',
  },
  {
    id: '58',
    name: 'Express',
    url: 'https://www.financialexpress.com/',
    images: 'https://i.ibb.co/0KkcC92/financialexpress.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a57',
  },
  {
    id: '59',
    name: 'Buzz Feed',
    url: 'https://www.buzzfeed.com/in',
    images: 'https://i.ibb.co/tCPXn60/buzzfeed.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a58',
  },
  {
    id: '60',
    name: 'The Quint',
    url: 'https://www.thequint.com/',
    images: 'https://i.ibb.co/tpKR8f6/quint.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a59',
  },
  {
    id: '61',
    name: 'Paytm',
    url: 'https://paytm.com/',
    images: 'https://i.ibb.co/zJ7PhQ3/paytm.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a60',
  },
  {
    id: '62',
    name: 'Mobikwik',
    url: 'https://www.mobikwik.com/',
    images: 'https://i.ibb.co/ncpfTk0/mobikwik-squarelogo-1517911658186.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a61',
  },
  {
    id: '63',
    name: 'Free Charge',
    url: 'https://www.freecharge.in/',
    images: 'https://i.ibb.co/7rbbkqs/freecharge.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a62',
  },
  {
    id: '64',
    name: 'Jio Savan',
    url: 'https://www.jiosaavn.com/',
    images: 'https://i.ibb.co/Rjp6WmS/saavn-icon-logo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a63',
  },
  {
    id: '65',
    name: 'Ganna',
    url: 'https://gaana.com/',
    images: 'https://i.ibb.co/mbs14Pk/ganna.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a64',
  },
  {
    id: '66',
    name: 'wynk',
    url: 'https://wynk.in/music',
    images: 'https://i.ibb.co/HHn009Z/wynk.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a65',
  },
  {
    id: '67',
    name: 'Hungama',
    url: 'https://www.hungama.com/',
    images: 'https://i.ibb.co/3hkSsfZ/hungama.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a66',
  },
  {
    id: '68',
    name: 'Naukri',
    url: 'https://www.naukri.com/',
    images: 'https://i.ibb.co/DQLnQ86/naukri.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a67',
  },
  {
    id: '69',
    name: 'Indeed',
    url: 'https://in.indeed.com/',
    images: 'https://i.ibb.co/YDhYDpp/indeed.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a68',
  },
  {
    id: '70',
    name: 'Monster',
    url: 'https://www.monsterindia.com/',
    images: 'https://i.ibb.co/ZmJZ3QS/monster.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a69',
  },
  {
    id: '71',
    name: 'Glassdoor',
    url: 'https://www.glassdoor.co.in/',
    images: 'https://i.ibb.co/M6WnfxM/glasdoor.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a70',
  },
  {
    id: '72',
    name: 'Crossnote',
    url: 'https://crossnote.app/',
    images: 'https://i.ibb.co/Vw69NMY/crossnote.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a71',
  },
  {
    id: '73',
    name: 'Weather',
    url: 'https://www.accuweather.com/',
    images: 'https://i.ibb.co/d7NscmY/accuweather.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a72',
  },
  {
    id: '74',
    name: 'Multicalc',
    url: 'https://www.multicalculator.app/calculator',
    images: 'https://i.ibb.co/tb3d9jj/multicalc.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a73',
  },
  {
    id: '75',
    name: 'Todolist',
    url: 'https://todoist.com/',
    images: 'https://i.ibb.co/kgt2HxL/todo.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a74',
  },
  {
    id: '76',
    name: 'Truecaller',
    url: 'https://www.truecaller.com/',
    images: 'https://i.ibb.co/RDHCnPW/truecaller.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a75',
  },
  {
    id: '77',
    name: 'LiveScore',
    url: 'https://www.cricbuzz.com/cricket-match/live-scores',
    images: 'https://i.ibb.co/fFyZPmJ/cricbuzz.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a76',
  },
  {
    id: '78',
    name: 'Horoscope',
    url: 'https://www.astrosage.com/horoscope/',
    images: 'https://i.ibb.co/F75tP54/horoscope.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a77',
  },
  {
    id: '79',
    name: 'Dictionary',
    url: ' https://www.dictionary.com/',
    images: 'https://i.ibb.co/QQ7rBmN/dictionary.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a78',
  },
  {
    id: '80',
    name: 'SpeedTest',
    url: 'https://www.speedtest.net/',
    images: 'https://i.ibb.co/df46Chb/speedtest.png',
    bgcolor: '#232F3E',
    type: 'app',
    uuid: 'a79',
  },
];

export {
  ShoppingApps,
  SocialApps,
  FoodApps,
  GroceryApps,
  MedicalApps,
  FurnitureApps,
  PopularApps,
  NewsApps,
  PayApps,
  MusicApps,
  JobsApps,
  ToolsApps,
  AllApps,
};
