const NewGames = [
  {
    id: '1',
    name: 'garden match',
    url: 'https://play.famobi.com/garden-match-3d',
    images: 'https://i.ibb.co/tYJXsYK/Garden-Match3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g1',
  },
  {
    id: '2',
    name: 'pull pins',
    url: 'https://play.famobi.com/pull-pins',
    images: 'https://i.ibb.co/zNyZ5yQ/Pull-Pins-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g116',
  },
  {
    id: '3',
    name: 'bubble tower',
    url: 'https://play.famobi.com/bubble-tower-3d',
    images: 'https://i.ibb.co/hRZQ7by/Bubble-Tower3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g117',
  },
  {
    id: '4',
    name: 'mahjong world',
    url: 'https://play.famobi.com/mahjong-world',
    images: 'https://i.ibb.co/s6tFY1q/Mahjong-World-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g33',
  },
  {
    id: '5',
    name: 'bus parking',
    url: 'https://play.famobi.com/bus-parking-3d',
    images: 'https://i.ibb.co/cX0NGKV/Bus-Parking3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g118',
  },
  {
    id: '6',
    name: 'crossover21',
    url: 'https://play.famobi.com/crossover-21',
    images: 'https://i.ibb.co/ydSRLpY/Crossover21-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g62',
  },
  {
    id: '7',
    name: 'crazy caves',
    url: 'https://play.famobi.com/crazy-caves',
    images: 'https://i.ibb.co/c2H3Gy0/Crazy-Caves-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g119',
  },
  {
    id: '8',
    name: 'hoop royale',
    url: 'https://play.famobi.com/hoop-royale',
    images: 'https://i.ibb.co/3RXS33m/Hoop-Royale-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g120',
  },
  {
    id: '9',
    name: 'tnt bomb',
    url: 'https://play.famobi.com/tnt-bomb',
    images: 'https://i.ibb.co/bQLJ02h/Tnt-Bomb-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g121',
  },
  {
    id: '10',
    name: 'smarty bubbles',
    url: 'https://play.famobi.com/smarty-bubbles-2',
    images: 'https://i.ibb.co/NYbZZpf/Smarty-Bubbles2-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g20',
  },
  {
    id: '11',
    name: 'stack smash',
    url: 'https://play.famobi.com/stack-smash',
    images: 'https://i.ibb.co/frJGnsm/Stack-Smash-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g122',
  },
  {
    id: '12',
    name: 'mahjong 3d',
    url: 'https://play.famobi.com/mahjong-3d',
    images: 'https://i.ibb.co/2q6Lg0d/Mahjong3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g34',
  },
  {
    id: '13',
    name: 'Domino Frenzy',
    url: 'https://play.famobi.com/domino-frenzy',
    images: 'https://i.ibb.co/s53zktR/Domino-Frenzy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g127',
  },
  {
    id: '14',
    name: 'monkey bounce',
    url: 'https://play.famobi.com/monkey-bounce',
    images: 'https://i.ibb.co/BfhZN0W/Monkey-Bounce-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g75',
  },
  {
    id: '15',
    name: 'curve ball',
    url: 'https://play.famobi.com/curve-ball-3d',
    images: 'https://i.ibb.co/P57nJkH/Curve-Ball3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g124',
  },
  {
    id: '16',
    name: 'slice rush',
    url: 'https://play.famobi.com/slice-rush',
    images: 'https://i.ibb.co/ckmdF1H/Slice-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g125',
  },
  {
    id: '17',
    name: 'hippo pizza',
    url: 'https://play.famobi.com/hippo-pizza-chef',
    images: 'https://i.ibb.co/chpycFb/Hippo-Pizza-Chef-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g126',
  },
  {
    id: '18',
    name: 'cannon balls',
    url: 'https://play.famobi.com/cannon-balls-3d',
    images: 'https://i.ibb.co/wpPJYZT/Cannon-Balls3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g128',
  },
  {
    id: '19',
    name: 'pets rush',
    url: 'https://play.famobi.com/pets-rush',
    images: 'https://i.ibb.co/Ch0kDpT/Pets-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g129',
  },
];

const BestGames = [
  {
    id: '1',
    name: 'element blocks',
    url: 'https://play.famobi.com/element-blocks',
    images: 'https://i.ibb.co/YcBLQvV/Element-Blocks-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g37',
  },
  {
    id: '2',
    name: 'pirate cards',
    url: 'https://play.famobi.com/pirate-cards',
    images: 'https://i.ibb.co/dbCcVgT/Pirate-Cards-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g63',
  },
  {
    id: '3',
    name: 'zoo boom',
    url: 'https://play.famobi.com/zoo-boom',
    images: 'https://i.ibb.co/CwbCC7H/Zoo-Boom-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g2',
  },
  {
    id: '4',
    name: 'moto x3m',
    url: 'https://play.famobi.com/moto-x3m-pool-party',
    images: 'https://i.ibb.co/NyyPNg5/Moto-X3m-Pool-Party-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g135',
  },
  {
    id: '5',
    name: 'perfect piano',
    url: 'https://play.famobi.com/perfect-piano',
    images: 'https://i.ibb.co/hCykXk7/Perfect-Piano-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g173',
  },
  {
    id: '6',
    name: 'bubble woods',
    url: 'https://play.famobi.com/bubble-woods',
    images: 'https://i.ibb.co/T8pq9NX/Bubble-Woods-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g3',
  },
  {
    id: '7',
    name: 'free kick',
    url: 'https://play.famobi.com/3d-free-kick',
    images: 'https://i.ibb.co/QdHK1Yd/3d-Free-Kick-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g161',
  },
  {
    id: '8',
    name: 'billiards',
    url: 'https://play.famobi.com/8-ball-billiards-classic',
    images: 'https://i.ibb.co/tzhPvZg/8-Ball-Billiards-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g168',
  },
  {
    id: '9',
    name: 'color pixel',
    url: 'https://play.famobi.com/color-pixel-art-classic',
    images: 'https://i.ibb.co/pKTRVJr/Color-Pixel-Art-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g49',
  },
  {
    id: '10',
    name: 'archery',
    url: 'https://play.famobi.com/archery-world-tour',
    images: 'https://i.ibb.co/pr8QjLD/Archery-World-Tour-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g169',
  },
  {
    id: '11',
    name: 'totemia',
    url: 'https://play.famobi.com/totemia-cursed-marbles',
    images: 'https://i.ibb.co/3khrQzV/Totemia-Cursed-Marbles-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g4',
  },
  {
    id: '12',
    name: 'gin rummy',
    url: 'https://play.famobi.com/gin-rummy-plus',
    images: 'https://i.ibb.co/1d2gkjX/Gin-Rummy-Plus-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g69',
  },
  {
    id: '13',
    name: 'TT',
    url: 'https://play.famobi.com/table-tennis-world-tour',
    images: 'https://i.ibb.co/McMZgBs/Table-Tennis-World-Tour-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g174',
  },
  {
    id: '14',
    name: 'klondike',
    url: 'https://play.famobi.com/solitaire-klondike',
    images: 'https://i.ibb.co/tpYHcGQ/Solitaire-Klondike-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g73',
  },
  {
    id: '15',
    name: 'onet connect',
    url: 'https://play.famobi.com/onet-connect-classic',
    images: 'https://i.ibb.co/PMKqVFH/Onet-Connect-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g175',
  },
  {
    id: '16',
    name: 'diamond rush',
    url: 'https://play.famobi.com/diamond-rush',
    images: 'https://i.ibb.co/hMYY8zZ/Diamond-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g14',
  },
  {
    id: '17',
    name: 'truck trials',
    url: 'https://play.famobi.com/truck-trials',
    images: 'https://i.ibb.co/5WLt4f5/Truck-Trials-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g147',
  },
  {
    id: '18',
    name: 'endless truck',
    url: 'https://play.famobi.com/endless-truck',
    images: 'https://i.ibb.co/8NSzY81/Endless-Truck-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g149',
  },
  {
    id: '19',
    name: 'candy bubble',
    url: 'https://play.famobi.com/candy-bubble',
    images: 'https://i.ibb.co/k3P9H6g/Candy-Bubble-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g176',
  },
];

const Match3Games = [
  {
    id: '1',
    name: 'garden match',
    url: 'https://play.famobi.com/garden-match-3d',
    images: 'https://i.ibb.co/6XmHG82/Garden-Match3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g1',
  },
  {
    id: '2',
    name: 'zoo boom',
    url: 'https://play.famobi.com/zoo-boom',
    images: 'https://i.ibb.co/y6rJcGh/Zoo-Boom-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g2',
  },
  {
    id: '3',
    name: 'bubble woods',
    url: 'https://play.famobi.com/bubble-woods',
    images: 'https://i.ibb.co/XVhZSxz/Bubble-Woods-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g3',
  },
  {
    id: '4',
    name: 'totemia',
    url: 'https://play.famobi.com/totemia-cursed-marbles',
    images: 'https://i.ibb.co/1Kjwq2C/Totemia-Cursed-Marbles-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g4',
  },
  {
    id: '5',
    name: 'jewel-aqua',
    url: 'https://play.famobi.com/jewel-aquarium',
    images: 'https://i.ibb.co/w6Z0nTh/Jewel-Aquarium-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g5',
  },
  {
    id: '6',
    name: 'jewel',
    url: 'https://play.famobi.com/jewel-christmas',
    images: 'https://i.ibb.co/9h6pNZz/Jewel-Christmas-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g6',
  },
  {
    id: '7',
    name: 'fire & fury',
    url: 'https://play.famobi.com/dragon-fire-and-fury',
    images: 'https://i.ibb.co/5Bqmvb4/Dragon-Fire-And-Fury-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g7',
  },
  {
    id: '8',
    name: 'fruit crush',
    url: 'https://play.famobi.com/fruit-crush-frenzy',
    images: 'https://i.ibb.co/8jKRd7t/Fruit-Crush-Frenzy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g8',
  },
  {
    id: '9',
    name: 'jewel duel',
    url: 'https://play.famobi.com/jewel-duel',
    images: 'https://i.ibb.co/DD1jX0Z/Jewel-Duel-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g9',
  },
  {
    id: '10',
    name: 'pirates',
    url: 'https://play.famobi.com/pirates-the-match-3',
    images: 'https://i.ibb.co/pvHn4Vb/Pirates-The-Match3-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g10',
  },
  {
    id: '11',
    name: 'momo pop',
    url: 'https://play.famobi.com/momo-pop',
    images: 'https://i.ibb.co/8bzv2nZ/Momo-Pop-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g11',
  },
  {
    id: '12',
    name: 'magic jewels',
    url: 'https://play.famobi.com/magic-jewels',
    images: 'https://i.ibb.co/NZntYtF/Magic-Jewels-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g12',
  },
  {
    id: '13',
    name: 'hex blitz',
    url: 'https://play.famobi.com/hex-blitz',
    images: 'https://i.ibb.co/mSH7d2g/Hex-Blitz-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g13',
  },
  {
    id: '14',
    name: 'diamond rush',
    url: 'https://play.famobi.com/diamond-rush',
    images: 'https://i.ibb.co/JxM7VH7/Diamond-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g14',
  },
  {
    id: '15',
    name: 'fruit pulp',
    url: 'https://play.famobi.com/fruit-pulp',
    images: 'https://i.ibb.co/dWPvhS1/Fruit-Pulp-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g15',
  },
  {
    id: '16',
    name: 'sailor pop',
    url: 'https://play.famobi.com/sailor-pop',
    images: 'https://i.ibb.co/rpCR7zF/Sailor-Pop-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g16',
  },
  {
    id: '17',
    name: 'jewels mania',
    url: 'https://play.famobi.com/jewels-mania',
    images: 'https://i.ibb.co/wYgVsQs/Jewels-Mania-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g17',
  },
  {
    id: '18',
    name: '11 11',
    url: 'https://play.famobi.com/11-11',
    images: 'https://i.ibb.co/JdfPfSd/Eleven-Eleven-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g18',
  },
  {
    id: '19',
    name: 'jewel jungle',
    url: 'https://play.famobi.com/jewel-jungle',
    images: 'https://i.ibb.co/QKgcKrm/Jewel-Jungle-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g19',
  },
];

const BubbleGames = [
  {
    id: '1',
    name: 'bubbles 2',
    url: 'https://play.famobi.com/smarty-bubbles-2',
    images: 'https://i.ibb.co/sCtgNFF/Smarty-Bubbles2-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g20',
  },
  {
    id: '2',
    name: 'woods',
    url: 'https://play.famobi.com/bubble-woods',
    images: 'https://i.ibb.co/XVhZSxz/Bubble-Woods-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g21',
  },
  {
    id: '3',
    name: 'candy',
    url: 'https://play.famobi.com/candy-bubble',
    images: 'https://i.ibb.co/FnH7kyZ/Candy-Bubble-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g22',
  },
  {
    id: '4',
    name: 'bubble',
    url: 'https://play.famobi.com/bubble-spirit',
    images: 'https://i.ibb.co/1d2RLjZ/Bubble-Spirit-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g23',
  },
  {
    id: '5',
    name: 'kitty',
    url: 'https://play.famobi.com/kitty-bubbles',
    images: 'https://i.ibb.co/82Hfy9k/Kitty-Bubbles-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g24',
  },
  {
    id: '7',
    name: 'shooter',
    url: 'https://play.famobi.com/sea-bubble-shooter',
    images: 'https://i.ibb.co/2KMf0SG/Sea-Bubble-Shooter-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g25',
  },
  {
    id: '8',
    name: 'soccer',
    url: 'https://play.famobi.com/soccer-bubbles',
    images: 'https://i.ibb.co/r0WmYsX/Soccer-Bubbles-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g26',
  },
  {
    id: '9',
    name: 'gems',
    url: 'https://play.famobi.com/bubble-gems',
    images: 'https://i.ibb.co/4SZg1MS/Bubble-Gems-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g27',
  },
  {
    id: '10',
    name: 'shooter',
    url: 'https://play.famobi.com/bubbles-shooter',
    images: 'https://i.ibb.co/T1cCnsx/Bubbles-Shooter-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g28',
  },
  {
    id: '11',
    name: 'hamsters',
    url: 'https://play.famobi.com/bubble-hamsters',
    images: 'https://i.ibb.co/tZMtNz1/Bubble-Hamsters-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g29',
  },
  {
    id: '12',
    name: 'bubble xmas',
    url: 'https://play.famobi.com/bubble-hamsters',
    images: 'https://i.ibb.co/dj5LgQF/Smarty-Bubbles-Xmas-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g30',
  },
  {
    id: '13',
    name: 'ranch',
    url: 'https://play.famobi.com/orange-ranch',
    images: 'https://i.ibb.co/LkcvHCN/Orange-Ranch-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g31',
  },
  {
    id: '14',
    name: 'orange',
    url: 'https://play.famobi.com/orange-bubbles',
    images: 'https://i.ibb.co/vxTF5DL/Orange-Bubbles-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g32',
  },
];

const PuzzleGames = [
  {
    id: '1',
    name: 'MahjongWorld',
    url: 'https://play.famobi.com/mahjong-world',
    images: 'https://i.ibb.co/c8dYp7X/Mahjong-World-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g33',
  },
  {
    id: '2',
    name: 'Mahjong3D',
    url: 'https://play.famobi.com/mahjong-3d',
    images: 'https://i.ibb.co/5vyhkKt/Mahjong3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g34',
  },
  {
    id: '3',
    name: 'onetworld',
    url: 'https://play.famobi.com/onet-world',
    images: 'https://i.ibb.co/9W0Wt1C/Onet-World-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g35',
  },
  {
    id: '4',
    name: 'zoo',
    url: 'https://play.famobi.com/blocks-puzzle-zoo',
    images: 'https://i.ibb.co/5WXX4C1/Blocks-Puzzle-Zoo-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g36',
  },
  {
    id: '5',
    name: 'blocks',
    url: 'https://play.famobi.com/element-blocks',
    images: 'https://i.ibb.co/wMt4rs2/Element-Blocks-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g37',
  },
  {
    id: '6',
    name: 'find-in',
    url: 'https://play.famobi.com/find-in-mind',
    images: 'https://i.ibb.co/KsLtGms/Find-In-Mind-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g38',
  },
  {
    id: '7',
    name: 'jewels',
    url: 'https://play.famobi.com/merge-jewels',
    images: 'https://i.ibb.co/hLbP5vD/Merge-Jewels-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g39',
  },
  {
    id: '8',
    name: 'maze',
    url: 'https://play.famobi.com/maze',
    images: 'https://i.ibb.co/v3HfDth/Maze-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g40',
  },
  {
    id: '9',
    name: '1000 blocks',
    url: 'https://play.famobi.com/1000-blocks',
    images: 'https://i.ibb.co/2hhMChx/1000-Blocks-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g41',
  },
  {
    id: '10',
    name: 'bunnyquest',
    url: 'https://play.famobi.com/bunny-quest',
    images: 'https://i.ibb.co/61fR15Z/Bunny-Quest-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g42',
  },
  {
    id: '11',
    name: 'jigsaw',
    url: 'https://play.famobi.com/jigsaw-puzzle-deluxe',
    images: 'https://i.ibb.co/fdFvDGX/Jigsaw-Puzzle-Deluxe-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g43',
  },
  {
    id: '12',
    name: 'water',
    url: 'https://play.famobi.com/tap-my-water',
    images: 'https://i.ibb.co/BGj7jXM/Tap-My-Water-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g44',
  },
  {
    id: '13',
    name: 'mahjong',
    url: 'https://play.famobi.com/mahjong-flowers',
    images: 'https://i.ibb.co/vJ9Vxv8/Mahjong-Flowers-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g45',
  },
  {
    id: '14',
    name: 'dominoes',
    url: 'https://play.famobi.com/dominoes-classic',
    images: 'https://i.ibb.co/m8SP602/Dominoes-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g46',
  },
  {
    id: '15',
    name: 'kittenmahjong',
    url: 'https://play.famobi.com/kitchen-mahjong-classic',
    images: 'https://i.ibb.co/QdDjQgd/Kitchen-Mahjong-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g47',
  },
  {
    id: '16',
    name: 'mahjong',
    url: 'https://play.famobi.com/mahjong-connect-classic',
    images: 'https://i.ibb.co/FmvkBRL/Mahjong-Connect-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g48',
  },
  {
    id: '17',
    name: 'pixel art',
    url: 'https://play.famobi.com/color-pixel-art-classic',
    images: 'https://i.ibb.co/WBQqwMm/Color-Pixel-Art-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g49',
  },
  {
    id: '18',
    name: 'word search',
    url: 'https://play.famobi.com/word-search-classic',
    images: 'https://i.ibb.co/Y3ZYzjG/Word-Search-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g50',
  },
  {
    id: '19',
    name: 'stacker',
    url: 'https://play.famobi.com/square-stacker',
    images: 'https://i.ibb.co/s6Pn0d1/Square-Stacker-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g51',
  },
];

const QuizGames = [
  {
    id: '1',
    name: '7 words',
    url: 'https://play.famobi.com/7-words',
    images: 'https://i.ibb.co/vx8gZfk/7-Words-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g52',
  },
  {
    id: '2',
    name: 'Alien',
    url: 'https://play.famobi.com/alien-quest',
    images: 'https://i.ibb.co/cJ8RHLx/Alien-Quest-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g53',
  },
  {
    id: '3',
    name: 'hangman',
    url: 'https://play.famobi.com/sweet-hangman',
    images: 'https://i.ibb.co/17QsSpr/Sweet-Hangman-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g54',
  },
  {
    id: '4',
    name: 'geo quiz',
    url: 'https://play.famobi.com/geo-quiz-europe',
    images: 'https://i.ibb.co/1z1qDy5/Geo-Quiz-Europe-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g55',
  },
  {
    id: '5',
    name: 'animal',
    url: 'https://play.famobi.com/animal-quiz',
    images: 'https://i.ibb.co/JyfFHB9/Animal-Quiz-Christmas-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g56',
  },
  {
    id: '6',
    name: 'fluffyegg',
    url: 'https://play.famobi.com/fluffy-egg',
    images: 'https://i.ibb.co/hYZnjGH/Fluffy-Egg-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g57',
  },
  {
    id: '7',
    name: 'wordguess4',
    url: 'https://play.famobi.com/wordguess-4images',
    images: 'https://i.ibb.co/FsMZ4jH/Wordguess4-Images-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g58',
  },
  {
    id: '8',
    name: 'Cat',
    url: 'https://play.famobi.com/what-famous-cat-are-you',
    images: 'https://i.ibb.co/qMJKgDG/What-Famous-Cat-Are-You-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g59',
  },
  {
    id: '9',
    name: 'wordheavy',
    url: 'https://play.famobi.com/wordguess-2-heavy',
    images: 'https://i.ibb.co/T2ysjG6/Wordguess2-Heavy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g60',
  },
  {
    id: '10',
    name: 'wordguess',
    url: 'https://play.famobi.com/wordguess-2-easy',
    images: 'https://i.ibb.co/bWH048T/Wordguess2-Easy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g61',
  },
];

const CardGames = [
  {
    id: '1',
    name: 'crossover',
    url: 'https://play.famobi.com/crossover-21',
    images: 'https://i.ibb.co/grKLbMR/Crossover21-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g62',
  },
  {
    id: '2',
    name: 'pirate',
    url: 'https://play.famobi.com/pirate-cards',
    images: 'https://i.ibb.co/3TFMmbW/Pirate-Cards-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g63',
  },
  {
    id: '3',
    name: 'legend',
    url: 'https://play.famobi.com/solitaire-legend',
    images: 'https://i.ibb.co/CzzqBP0/Solitaire-Legend-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g64',
  },
  {
    id: '4',
    name: 'solitaire',
    url: 'https://play.famobi.com/solitaire-classic-christmas',
    images: 'https://i.ibb.co/vcgsNgG/Solitaire-Classic-Christmas-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g65',
  },
  {
    id: '5',
    name: 'mafia poker',
    url: 'https://play.famobi.com/mafia-poker',
    images: 'https://i.ibb.co/Mhd66fM/Mafia-Poker-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g66',
  },
  {
    id: '6',
    name: 'matchcard',
    url: 'https://play.famobi.com/matching-card-heroes',
    images: 'https://i.ibb.co/YQ4vtFz/Matching-Card-Heroes-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g67',
  },
  {
    id: '7',
    name: 'kitten',
    url: 'https://play.famobi.com/kitten-match',
    images: 'https://i.ibb.co/DY17cdJ/Kitten-Match-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g68',
  },
  {
    id: '8',
    name: 'rummy',
    url: 'https://play.famobi.com/gin-rummy-plus',
    images: 'https://i.ibb.co/d0dX2bx/Gin-Rummy-Plus-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g69',
  },
  {
    id: '9',
    name: 'solitaire',
    url: 'https://play.famobi.com/3d-solitaire',
    images: 'https://i.ibb.co/3021Rcn/3d-Solitaire-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g70',
  },
  {
    id: '10',
    name: 'cards',
    url: 'https://play.famobi.com/duo-cards',
    images: 'https://i.ibb.co/RcGzQpd/Duo-Cards-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g71',
  },
  {
    id: '11',
    name: 'blackjack',
    url: 'https://play.famobi.com/blackjack-bet',
    images: 'https://i.ibb.co/Kj685fh/Black-Jack-Bet-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g72',
  },
  {
    id: '12',
    name: 'klondike',
    url: 'https://play.famobi.com/solitaire-klondike',
    images: 'https://i.ibb.co/W3PzpPr/Solitaire-Klondike-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g73',
  },
  {
    id: '13',
    name: 'freecell',
    url: 'https://play.famobi.com/freecell-solitaire-classic',
    images: 'https://i.ibb.co/Y2hmT5k/Free-Cell-Solitaire-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g74',
  },
  {
    id: '14',
    name: 'tri peak',
    url: 'https://play.famobi.com/monkey-bounce',
    images: 'https://i.ibb.co/jZSjxWv/Tri-Peaks-Solitaire-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g75',
  },
  {
    id: '15',
    name: 'kk tri',
    url: 'https://play.famobi.com/kk-tri-towers-solitaire',
    images: 'https://i.ibb.co/ZzD0qHq/Kk-Tri-Towers-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g76',
  },
  {
    id: '16',
    name: 'spider',
    url: 'https://play.famobi.com/spider-solitaire-classic',
    images: 'https://i.ibb.co/fq2YFBK/Spider-Solitaire-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g77',
  },
  {
    id: '17',
    name: 'classic',
    url: 'https://play.famobi.com/western-solitaire',
    images: 'https://i.ibb.co/NjbsN86/Western-Solitaire-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g78',
  },
  {
    id: '18',
    name: 'solitaire-master',
    url: 'https://play.famobi.com/solitaire-master',
    images: 'https://i.ibb.co/SB77sdr/Solitaire-Master-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g79',
  },
  {
    id: '19',
    name: 'solitaire',
    url: 'https://play.famobi.com/solitaire-classic-easter',
    images: 'https://i.ibb.co/2Skz3mM/Solitaire-Classic-Easter-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g80',
  },
];

const GirlGames = [
  {
    id: '1',
    name: 'Surgery',
    url: 'https://play.famobi.com/emergency-surgery',
    images: 'https://i.ibb.co/Prp5C6v/Emergency-Surgery-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g81',
  },
  {
    id: '2',
    name: 'kawaii',
    url: 'https://play.famobi.com/kawaii-chibi-creator',
    images: 'https://i.ibb.co/Hz1d1bG/Kawaii-Chibi-Creator-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g82',
  },
  {
    id: '3',
    name: 'lily birthday',
    url: 'https://play.famobi.com/baby-lily-birthday',
    images: 'https://i.ibb.co/Vm0S3QH/Baby-Lily-Birthday-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g83',
  },
  {
    id: '4',
    name: 'pie',
    url: 'https://play.famobi.com/pie-realife-cooking',
    images: 'https://i.ibb.co/mcRkmLm/Pie-Realife-Cooking-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g84',
  },
  {
    id: '5',
    name: 'baby lily',
    url: 'https://play.famobi.com/baby-lily-care',
    images: 'https://i.ibb.co/rMc1RB2/Baby-Lily-Care-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g85',
  },
  {
    id: '6',
    name: 'baby lily',
    url: 'https://play.famobi.com/baby-lily-sick-day',
    images: 'https://i.ibb.co/m48yfCM/Baby-Lily-Sick-Day-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g86',
  },
  {
    id: '7',
    name: 'deer',
    url: 'https://play.famobi.com/my-fairytale-deer',
    images: 'https://i.ibb.co/qRbLYCS/My-Fairytale-Deer-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g87',
  },
  {
    id: '8',
    name: 'waterhorse',
    url: 'https://play.famobi.com/my-fairytale-water-horse',
    images: 'https://i.ibb.co/DMFnttS/My-Fairytale-Water-Horse-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g88',
  },
  {
    id: '9',
    name: 'panda',
    url: 'https://play.famobi.com/happy-panda',
    images: 'https://i.ibb.co/HzP1jCX/Happy-Panda-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g89',
  },
  {
    id: '10',
    name: 'koala',
    url: 'https://play.famobi.com/happy-koala',
    images: 'https://i.ibb.co/5sZpTfV/Happy-Koala-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g90',
  },
  {
    id: '11',
    name: 'sailorgirls',
    url: 'https://play.famobi.com/sailor-girls-avatar-maker',
    images: 'https://i.ibb.co/R3TZc32/Sailor-Girls-Avatar-Maker-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g91',
  },
  {
    id: '12',
    name: 'animefantasy',
    url: 'https://play.famobi.com/3d-anime-fantasy',
    images: 'https://i.ibb.co/FHS12qQ/3d-Anime-Fantasy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g92',
  },
  {
    id: '13',
    name: 'unicorncare',
    url: 'https://play.famobi.com/cute-unicorn-care',
    images: 'https://i.ibb.co/bHMw4QP/Cute-Unicorn-Care-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g93',
  },
  {
    id: '14',
    name: 'fairytale',
    url: 'https://play.famobi.com/my-fairytale-tiger',
    images: 'https://i.ibb.co/jVjF9LG/My-Fairytale-Tiger-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g94',
  },
  {
    id: '15',
    name: 'lemur',
    url: 'https://play.famobi.com/happy-lemur',
    images: 'https://i.ibb.co/y5wLdkH/Happy-Lemur-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g95',
  },
];

const JumpGames = [
  {
    id: '1',
    name: 'jungle',
    url: 'https://play.famobi.com/jungle-run',
    images: 'https://i.ibb.co/94K1hws/Jungle-Run-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g96',
  },
  {
    id: '2',
    name: 'banana',
    url: 'https://play.famobi.com/banana-run',
    images: 'https://i.ibb.co/KKTLd20/Banana-Run-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g97',
  },
  {
    id: '3',
    name: 'outcome',
    url: 'https://play.famobi.com/outcome',
    images: 'https://i.ibb.co/5BnSYvL/Outcome-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g98',
  },
  {
    id: '4',
    name: 'yeti-sensa',
    url: 'https://play.famobi.com/yeti-sensation',
    images: 'https://i.ibb.co/3pRP2Xt/Yeti-Sensation-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g99',
  },
  {
    id: '5',
    name: 'greedy',
    url: 'https://play.famobi.com/greedy-rabbit',
    images: 'https://i.ibb.co/V3fmYkM/Greedy-Rabbit-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g100',
  },
  {
    id: '6',
    name: 'snowball',
    url: 'https://play.famobi.com/snowball-christmas-world',
    images: 'https://i.ibb.co/bQtkZn0/Snowball-Christmas-World-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g101',
  },
  {
    id: '7',
    name: 'basket-ball',
    url: 'https://play.famobi.com/basket-and-ball',
    images: 'https://i.ibb.co/KyPyryH/Basket-And-Ball-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g102',
  },
  {
    id: '8',
    name: 'snowball',
    url: 'https://play.famobi.com/snowball-world',
    images: 'https://i.ibb.co/f1NbQyG/Snowball-World-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g103',
  },
  {
    id: '9',
    name: 'key-shield',
    url: 'https://play.famobi.com/key-and-shield',
    images: 'https://i.ibb.co/v4Lp3db/Key-And-Shield-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g104',
  },
  {
    id: '10',
    name: 'jack',
    url: 'https://play.famobi.com/running-jack',
    images: 'https://i.ibb.co/yygGhcj/Running-Jack-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g105',
  },
  {
    id: '11',
    name: 'goldblade',
    url: 'https://play.famobi.com/princess-goldblade',
    images: 'https://i.ibb.co/KK33Q1J/Princess-Goldblade-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g106',
  },
  {
    id: '12',
    name: 'monster',
    url: 'https://play.famobi.com/sweets-monster',
    images: 'https://i.ibb.co/VwTL27G/Sweets-Monster-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g107',
  },
  {
    id: '13',
    name: 'the green',
    url: 'https://play.famobi.com/the-green-mission',
    images: 'https://i.ibb.co/gwfYthb/The-Green-Mission-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g108',
  },
  {
    id: '14',
    name: 'nut rush 3',
    url: 'https://play.famobi.com/nut-rush3',
    images: 'https://i.ibb.co/277WkWp/Nut-Rush3-Christmas-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g109',
  },
  {
    id: '15',
    name: 'red head',
    url: 'https://play.famobi.com/red-head',
    images: 'https://i.ibb.co/V3JT8KJ/Red-Head-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g110',
  },
  {
    id: '16',
    name: 'kk shadow',
    url: 'https://play.famobi.com/kk-shadow-run',
    images: 'https://i.ibb.co/2ZHqngM/Kiba-Kumba-Shadow-Run-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g111',
  },
  {
    id: '17',
    name: 'highjump',
    url: 'https://play.famobi.com/highjump',
    images: 'https://i.ibb.co/VSRMxmT/High-Jump-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g112',
  },
  {
    id: '18',
    name: 'kk jungle',
    url: 'https://play.famobi.com/kk-jungle-chaos',
    images: 'https://i.ibb.co/z7mTdMd/Jungle-Chaos-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g113',
  },
  {
    id: '19',
    name: 'ufo run',
    url: 'https://play.famobi.com/ufo-run',
    images: 'https://i.ibb.co/sQgrqV1/Ufo-Run-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g114',
  },
  {
    id: '20',
    name: 'nut rush2',
    url: 'https://play.famobi.com/nut-rush2',
    images: 'https://i.ibb.co/RDZHvKX/Nut-Rush2-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g115',
  },
];

const ArcadeGames = [
  {
    id: '1',
    name: 'pull pins',
    url: 'https://play.famobi.com/pull-pins',
    images: 'https://i.ibb.co/37kfGY5/Pull-Pins-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g116',
  },
  {
    id: '2',
    name: 'bubble tower',
    url: 'https://play.famobi.com/bubble-tower-3d',
    images: 'https://i.ibb.co/WKZ0Y5M/Bubble-Tower3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g117',
  },
  {
    id: '3',
    name: 'bus parking',
    url: 'https://play.famobi.com/bus-parking-3d',
    images: 'https://i.ibb.co/M16fMRd/Bus-Parking3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g118',
  },
  {
    id: '4',
    name: 'crazy caves',
    url: 'https://play.famobi.com/crazy-caves',
    images: 'https://i.ibb.co/Cn5FZVd/Crazy-Caves-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g119',
  },
  {
    id: '5',
    name: 'hoop royale',
    url: 'https://play.famobi.com/hoop-royale',
    images: 'https://i.ibb.co/wCmXwJG/Hoop-Royale-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g120',
  },
  {
    id: '6',
    name: 'tnt bomb',
    url: 'https://play.famobi.com/tnt-bomb',
    images: 'https://i.ibb.co/c2ST7P6/Tnt-Bomb-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g121',
  },
  {
    id: '7',
    name: 'stack smash',
    url: 'https://play.famobi.com/stack-smash',
    images: 'https://i.ibb.co/XttxFwM/Stack-Smash-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g122',
  },
  {
    id: '8',
    name: 'monkey bounce',
    url: 'https://play.famobi.com/monkey-bounce',
    images: 'https://i.ibb.co/mDZg73t/Monkey-Bounce-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g123',
  },
  {
    id: '9',
    name: 'curve ball',
    url: 'https://play.famobi.com/curve-ball-3d',
    images: 'https://i.ibb.co/dW4K13r/Curve-Ball3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g124',
  },
  {
    id: '10',
    name: 'slice rush',
    url: 'https://play.famobi.com/slice-rush',
    images: 'https://i.ibb.co/BjB926t/Slice-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g125',
  },
  {
    id: '11',
    name: 'hippo pizza',
    url: 'https://play.famobi.com/hippo-pizza-chef',
    images: 'https://i.ibb.co/rthXWr9/Hippo-Pizza-Chef-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g126',
  },
  {
    id: '12',
    name: 'domino frenzy',
    url: 'https://play.famobi.com/domino-frenzy',
    images: 'https://i.ibb.co/xgMp5Jj/Domino-Frenzy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g127',
  },
  {
    id: '13',
    name: 'cannon balls',
    url: 'https://play.famobi.com/cannon-balls-3d',
    images: 'https://i.ibb.co/xsT3H15/Cannon-Balls3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g128',
  },
  {
    id: '14',
    name: 'pets rush',
    url: 'https://play.famobi.com/pets-rush',
    images: 'https://i.ibb.co/9yLT7WF/Pets-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g129',
  },
  {
    id: '15',
    name: 'zoo feeder',
    url: 'https://play.famobi.com/zoo-feeder',
    images: 'https://i.ibb.co/8YMLdqX/Zoo-Feeder-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g130',
  },
  {
    id: '16',
    name: 'element balls',
    url: 'https://play.famobi.com/element-balls',
    images: 'https://i.ibb.co/mXnFfSS/Element-Balls-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g131',
  },
  {
    id: '17',
    name: 'tower crash',
    url: 'https://play.famobi.com/tower-crash-3d',
    images: 'https://i.ibb.co/wQgGdR7/Tower-Crash3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g132',
  },
  {
    id: '18',
    name: 'sushi roll',
    url: 'https://play.famobi.com/sushi-roll',
    images: 'https://i.ibb.co/yhfKL86/Sushi-Roll-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g133',
  },
  {
    id: '19',
    name: 'knife rain',
    url: 'https://play.famobi.com/knife-rain',
    images: 'https://i.ibb.co/F8yb54F/Knife-Rain-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g134',
  },
];

const RacingGames = [
  {
    id: '1',
    name: 'motoparty',
    url: 'https://play.famobi.com/moto-x3m-pool-party',
    images: 'https://i.ibb.co/sHTsXx6/Moto-X3m-Pool-Party-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g135',
  },
  {
    id: '2',
    name: 'drivers',
    url: 'https://play.famobi.com/adventure-drivers',
    images: 'https://i.ibb.co/KLM0vk9/Adventure-Drivers-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g136',
  },
  {
    id: '3',
    name: 'moto x3m',
    url: 'https://play.famobi.com/moto-x3m',
    images: 'https://i.ibb.co/LC6RLW9/Moto-X3m-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g137',
  },
  {
    id: '4',
    name: 'high hills',
    url: 'https://play.famobi.com/high-hills',
    images: 'https://i.ibb.co/gJVcJPD/High-Hills-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g138',
  },
  {
    id: '5',
    name: 'drag racing',
    url: 'https://play.famobi.com/drag-racing-club',
    images: 'https://i.ibb.co/GpmZ9PJ/Drag-Racing-Club-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g139',
  },
  {
    id: '6',
    name: 'race right',
    url: 'https://play.famobi.com/race-right',
    images: 'https://i.ibb.co/rd0p4Gp/Race-Right-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g140',
  },
  {
    id: '7',
    name: 'biker street',
    url: 'https://play.famobi.com/biker-street',
    images: 'https://i.ibb.co/PFTLfgr/Biker-Street-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g141',
  },
  {
    id: '8',
    name: 'highway rider',
    url: 'https://play.famobi.com/highway-rider-extreme',
    images: 'https://i.ibb.co/rQPCKTr/Highway-Rider-Extreme-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g142',
  },
  {
    id: '9',
    name: 'moto fury',
    url: 'https://play.famobi.com/moto-fury',
    images: 'https://i.ibb.co/BsxmygR/Moto-Fury-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g143',
  },
  {
    id: '10',
    name: 'drift cup',
    url: 'https://play.famobi.com/drift-cup-racing',
    images: 'https://i.ibb.co/pQKhHfk/Drift-Cup-Racing-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g144',
  },
  {
    id: '11',
    name: 'trucks',
    url: 'https://play.famobi.com/racing-monster-trucks',
    images: 'https://i.ibb.co/dWjMXWX/Racing-Monster-Trucks-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g145',
  },
  {
    id: '12',
    name: 'cars',
    url: 'https://play.famobi.com/racing-cars',
    images: 'https://i.ibb.co/56ydfyD/Racing-Cars-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g146',
  },
  {
    id: '13',
    name: 'truck trials',
    url: 'https://play.famobi.com/truck-trials',
    images: 'https://i.ibb.co/NND1vLJ/Truck-Trials-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g147',
  },
  {
    id: '14',
    name: 'thug racer',
    url: 'https://play.famobi.com/thug-racer',
    images: 'https://i.ibb.co/12GHSvJ/Thug-Racer-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g148',
  },
  {
    id: '15',
    name: 'truck',
    url: 'https://play.famobi.com/endless-truck',
    images: 'https://i.ibb.co/ZJn8ZCT/Endless-Truck-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g149',
  },
  {
    id: '16',
    name: 'rival rush',
    url: 'https://play.famobi.com/rival-rush',
    images: 'https://i.ibb.co/kqM0YVc/Rival-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g150',
  },
  {
    id: '17',
    name: 'street',
    url: 'https://play.famobi.com/street-pursuit',
    images: 'https://i.ibb.co/QKg3NkS/Street-Pursuit-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g151',
  },
  {
    id: '18',
    name: 'streetrace',
    url: 'https://play.famobi.com/streetrace-fury',
    images: 'https://i.ibb.co/WkPDv9b/Street-Race-Fury-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g152',
  },
  {
    id: '19',
    name: '2 cars',
    url: 'https://play.famobi.com/2cars',
    images: 'https://i.ibb.co/MCS8R7X/2-Cars-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g153',
  },
];

const SportsGames = [
  {
    id: '1',
    name: 'drag racing',
    url: 'https://play.famobi.com/drag-racing-club',
    images: 'https://i.ibb.co/GpmZ9PJ/Drag-Racing-Club-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g154',
  },
  {
    id: '2',
    name: 'basketball',
    url: 'https://play.famobi.com/3d-basketball',
    images: 'https://i.ibb.co/DgzTxj1/3d-Basketball-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g155',
  },
  {
    id: '3',
    name: 'darts',
    url: 'https://play.famobi.com/3d-darts',
    images: 'https://i.ibb.co/6yNqr6P/3d-Darts-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g156',
  },
  {
    id: '4',
    name: 'dunk brush',
    url: 'https://play.famobi.com/dunk-brush',
    images: 'https://i.ibb.co/NY0smbG/Dunk-Brush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g157',
  },
  {
    id: '5',
    name: 'goalkeeper',
    url: 'https://play.famobi.com/goalkeeper-champ',
    images: 'https://i.ibb.co/nLZYp6c/Goalkeeper-Champ-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g158',
  },
  {
    id: '6',
    name: 'blaze kick',
    url: 'https://play.famobi.com/blaze-kick',
    images: 'https://i.ibb.co/5ssTTvy/Blaze-Kick-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g159',
  },
  {
    id: '7',
    name: 'cheap golf',
    url: 'https://play.famobi.com/cheap-golf',
    images: 'https://i.ibb.co/qg6CT78/Cheap-Golf-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g160',
  },
  {
    id: '8',
    name: 'free kick',
    url: 'https://play.famobi.com/3d-free-kick-world-cup-18',
    images: 'https://i.ibb.co/5YQvqRV/3d-Free-Kick-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g161',
  },
  {
    id: '9',
    name: 'air hockey',
    url: 'https://play.famobi.com/3d-air-hockey',
    images: 'https://i.ibb.co/yVghVjJ/3d-Air-Hockey-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g162',
  },
  {
    id: '10',
    name: 'soccer',
    url: 'https://play.famobi.com/soccer-champ-2018',
    images: 'https://i.ibb.co/1fgJwNt/Soccer-Champ2018-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g163',
  },
  {
    id: '11',
    name: '3d bowling',
    url: 'https://play.famobi.com/3d-bowling',
    images: 'https://i.ibb.co/KNx2bj1/3d-Bowling-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g164',
  },
  {
    id: '12',
    name: 'free kick',
    url: 'https://play.famobi.com/3d-free-kick',
    images: 'https://i.ibb.co/tJTRtPD/3d-Free-Kick-World-Cup18-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g165',
  },
  {
    id: '13',
    name: 'soccercup',
    url: 'https://play.famobi.com/soccertastic-world-cup-18',
    images: 'https://i.ibb.co/YpTm4bf/Soccertastic-World-Cup18-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g166',
  },
  {
    id: '14',
    name: 'penality',
    url: 'https://play.famobi.com/world-cup-penalty-2018',
    images: 'https://i.ibb.co/F4FBsgp/World-Cup-Penalty-2018-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g167',
  },
  {
    id: '15',
    name: 'billiards',
    url: 'https://play.famobi.com/8-ball-billiards-classic',
    images: 'https://i.ibb.co/qFSFNmv/8-Ball-Billiards-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g168',
  },
  {
    id: '16',
    name: 'archery',
    url: 'https://play.famobi.com/archery-world-tour',
    images: 'https://i.ibb.co/VTK2SJr/Archery-World-Tour-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g169',
  },
  {
    id: '17',
    name: 'street hoops',
    url: 'https://play.famobi.com/street-hoops-3d',
    images: 'https://i.ibb.co/R6nWj8c/Street-Hoops3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g170',
  },
  {
    id: '18',
    name: 'slam dunk',
    url: 'https://play.famobi.com/slam-dunk-basketball',
    images: 'https://i.ibb.co/SBF12Sw/Slam-Dunk-Basketball-Teaser-B.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g171',
  },
  {
    id: '19',
    name: 'moto fury',
    url: 'https://play.famobi.com/moto-fury',
    images: 'https://i.ibb.co/BsxmygR/Moto-Fury-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g172',
  },
];

const AllGames = [
  {
    id: '1',
    name: 'garden match',
    url: 'https://play.famobi.com/garden-match-3d',
    images: 'https://i.ibb.co/6XmHG82/Garden-Match3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g1',
  },
  {
    id: '2',
    name: 'zoo boom',
    url: 'https://play.famobi.com/zoo-boom',
    images: 'https://i.ibb.co/y6rJcGh/Zoo-Boom-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g2',
  },
  {
    id: '3',
    name: 'bubble woods',
    url: 'https://play.famobi.com/bubble-woods',
    images: 'https://i.ibb.co/XVhZSxz/Bubble-Woods-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g3',
  },
  {
    id: '4',
    name: 'totemia',
    url: 'https://play.famobi.com/totemia-cursed-marbles',
    images: 'https://i.ibb.co/1Kjwq2C/Totemia-Cursed-Marbles-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g4',
  },
  {
    id: '5',
    name: 'jewel-aqua',
    url: 'https://play.famobi.com/jewel-aquarium',
    images: 'https://i.ibb.co/w6Z0nTh/Jewel-Aquarium-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g5',
  },
  {
    id: '6',
    name: 'jewel',
    url: 'https://play.famobi.com/jewel-christmas',
    images: 'https://i.ibb.co/9h6pNZz/Jewel-Christmas-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g6',
  },
  {
    id: '7',
    name: 'fire & fury',
    url: 'https://play.famobi.com/dragon-fire-and-fury',
    images: 'https://i.ibb.co/5Bqmvb4/Dragon-Fire-And-Fury-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g7',
  },
  {
    id: '8',
    name: 'fruit crush',
    url: 'https://play.famobi.com/fruit-crush-frenzy',
    images: 'https://i.ibb.co/8jKRd7t/Fruit-Crush-Frenzy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g8',
  },
  {
    id: '9',
    name: 'jewel duel',
    url: 'https://play.famobi.com/jewel-duel',
    images: 'https://i.ibb.co/DD1jX0Z/Jewel-Duel-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g9',
  },
  {
    id: '10',
    name: 'pirates',
    url: 'https://play.famobi.com/pirates-the-match-3',
    images: 'https://i.ibb.co/pvHn4Vb/Pirates-The-Match3-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g10',
  },
  {
    id: '11',
    name: 'momo pop',
    url: 'https://play.famobi.com/momo-pop',
    images: 'https://i.ibb.co/8bzv2nZ/Momo-Pop-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g11',
  },
  {
    id: '12',
    name: 'magic jewels',
    url: 'https://play.famobi.com/magic-jewels',
    images: 'https://i.ibb.co/NZntYtF/Magic-Jewels-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g12',
  },
  {
    id: '13',
    name: 'hex blitz',
    url: 'https://play.famobi.com/hex-blitz',
    images: 'https://i.ibb.co/mSH7d2g/Hex-Blitz-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g13',
  },
  {
    id: '14',
    name: 'diamond rush',
    url: 'https://play.famobi.com/diamond-rush',
    images: 'https://i.ibb.co/JxM7VH7/Diamond-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g14',
  },
  {
    id: '15',
    name: 'fruit pulp',
    url: 'https://play.famobi.com/fruit-pulp',
    images: 'https://i.ibb.co/dWPvhS1/Fruit-Pulp-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g15',
  },
  {
    id: '16',
    name: 'sailor pop',
    url: 'https://play.famobi.com/sailor-pop',
    images: 'https://i.ibb.co/rpCR7zF/Sailor-Pop-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g16',
  },
  {
    id: '17',
    name: 'jewels mania',
    url: 'https://play.famobi.com/jewels-mania',
    images: 'https://i.ibb.co/wYgVsQs/Jewels-Mania-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g17',
  },
  {
    id: '18',
    name: '11 11',
    url: 'https://play.famobi.com/11-11',
    images: 'https://i.ibb.co/JdfPfSd/Eleven-Eleven-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g18',
  },
  {
    id: '19',
    name: 'jewel jungle',
    url: 'https://play.famobi.com/jewel-jungle',
    images: 'https://i.ibb.co/QKgcKrm/Jewel-Jungle-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g19',
  },
  {
    id: '20',
    name: 'bubbles 2',
    url: 'https://play.famobi.com/smarty-bubbles-2',
    images: 'https://i.ibb.co/sCtgNFF/Smarty-Bubbles2-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g20',
  },
  {
    id: '21',
    name: 'woods',
    url: 'https://play.famobi.com/bubble-woods',
    images: 'https://i.ibb.co/XVhZSxz/Bubble-Woods-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g21',
  },
  {
    id: '22',
    name: 'candy',
    url: 'https://play.famobi.com/candy-bubble',
    images: 'https://i.ibb.co/FnH7kyZ/Candy-Bubble-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g22',
  },
  {
    id: '23',
    name: 'bubble',
    url: 'https://play.famobi.com/bubble-spirit',
    images: 'https://i.ibb.co/1d2RLjZ/Bubble-Spirit-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g23',
  },
  {
    id: '24',
    name: 'kitty',
    url: 'https://play.famobi.com/kitty-bubbles',
    images: 'https://i.ibb.co/82Hfy9k/Kitty-Bubbles-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g24',
  },
  {
    id: '25',
    name: 'shooter',
    url: 'https://play.famobi.com/sea-bubble-shooter',
    images: 'https://i.ibb.co/2KMf0SG/Sea-Bubble-Shooter-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g25',
  },
  {
    id: '26',
    name: 'soccer',
    url: 'https://play.famobi.com/soccer-bubbles',
    images: 'https://i.ibb.co/r0WmYsX/Soccer-Bubbles-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g26',
  },
  {
    id: '27',
    name: 'gems',
    url: 'https://play.famobi.com/bubble-gems',
    images: 'https://i.ibb.co/4SZg1MS/Bubble-Gems-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g27',
  },
  {
    id: '28',
    name: 'shooter',
    url: 'https://play.famobi.com/bubbles-shooter',
    images: 'https://i.ibb.co/T1cCnsx/Bubbles-Shooter-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: '28',
  },
  {
    id: '29',
    name: 'hamsters',
    url: 'https://play.famobi.com/bubble-hamsters',
    images: 'https://i.ibb.co/tZMtNz1/Bubble-Hamsters-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g29',
  },
  {
    id: '30',
    name: 'bubble xmas',
    url: 'https://play.famobi.com/bubble-hamsters',
    images: 'https://i.ibb.co/dj5LgQF/Smarty-Bubbles-Xmas-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g30',
  },
  {
    id: '31',
    name: 'ranch',
    url: 'https://play.famobi.com/orange-ranch',
    images: 'https://i.ibb.co/LkcvHCN/Orange-Ranch-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g31',
  },
  {
    id: '32',
    name: 'orange',
    url: 'https://play.famobi.com/orange-bubbles',
    images: 'https://i.ibb.co/vxTF5DL/Orange-Bubbles-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g32',
  },
  {
    id: '33',
    name: 'MahjongWorld',
    url: 'https://play.famobi.com/mahjong-world',
    images: 'https://i.ibb.co/c8dYp7X/Mahjong-World-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g33',
  },
  {
    id: '34',
    name: 'Mahjong3D',
    url: 'https://play.famobi.com/mahjong-3d',
    images: 'https://i.ibb.co/5vyhkKt/Mahjong3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g34',
  },
  {
    id: '35',
    name: 'onetworld',
    url: 'https://play.famobi.com/onet-world',
    images: 'https://i.ibb.co/9W0Wt1C/Onet-World-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g35',
  },
  {
    id: '36',
    name: 'zoo',
    url: 'https://play.famobi.com/blocks-puzzle-zoo',
    images: 'https://i.ibb.co/5WXX4C1/Blocks-Puzzle-Zoo-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g36',
  },
  {
    id: '37',
    name: 'blocks',
    url: 'https://play.famobi.com/element-blocks',
    images: 'https://i.ibb.co/wMt4rs2/Element-Blocks-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g37',
  },
  {
    id: '38',
    name: 'find-in',
    url: 'https://play.famobi.com/find-in-mind',
    images: 'https://i.ibb.co/KsLtGms/Find-In-Mind-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g38',
  },
  {
    id: '39',
    name: 'jewels',
    url: 'https://play.famobi.com/merge-jewels',
    images: 'https://i.ibb.co/hLbP5vD/Merge-Jewels-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g39',
  },
  {
    id: '40',
    name: 'maze',
    url: 'https://play.famobi.com/maze',
    images: 'https://i.ibb.co/v3HfDth/Maze-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g40',
  },
  {
    id: '41',
    name: '1000 blocks',
    url: 'https://play.famobi.com/1000-blocks',
    images: 'https://i.ibb.co/2hhMChx/1000-Blocks-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g41',
  },
  {
    id: 'g42',
    name: 'bunnyquest',
    url: 'https://play.famobi.com/bunny-quest',
    images: 'https://i.ibb.co/61fR15Z/Bunny-Quest-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g42',
  },
  {
    id: 'g43',
    name: 'jigsaw',
    url: 'https://play.famobi.com/jigsaw-puzzle-deluxe',
    images: 'https://i.ibb.co/fdFvDGX/Jigsaw-Puzzle-Deluxe-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g43',
  },
  {
    id: '44',
    name: 'water',
    url: 'https://play.famobi.com/tap-my-water',
    images: 'https://i.ibb.co/BGj7jXM/Tap-My-Water-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g44',
  },
  {
    id: '45',
    name: 'mahjong',
    url: 'https://play.famobi.com/mahjong-flowers',
    images: 'https://i.ibb.co/vJ9Vxv8/Mahjong-Flowers-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g45',
  },
  {
    id: '46',
    name: 'dominoes',
    url: 'https://play.famobi.com/dominoes-classic',
    images: 'https://i.ibb.co/m8SP602/Dominoes-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g46',
  },
  {
    id: '47',
    name: 'kittenmahjong',
    url: 'https://play.famobi.com/kitchen-mahjong-classic',
    images: 'https://i.ibb.co/QdDjQgd/Kitchen-Mahjong-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g47',
  },
  {
    id: '48',
    name: 'mahjong',
    url: 'https://play.famobi.com/mahjong-connect-classic',
    images: 'https://i.ibb.co/FmvkBRL/Mahjong-Connect-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g48',
  },
  {
    id: '49',
    name: 'pixel art',
    url: 'https://play.famobi.com/color-pixel-art-classic',
    images: 'https://i.ibb.co/WBQqwMm/Color-Pixel-Art-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g49',
  },
  {
    id: '50',
    name: 'word search',
    url: 'https://play.famobi.com/word-search-classic',
    images: 'https://i.ibb.co/Y3ZYzjG/Word-Search-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g50',
  },
  {
    id: '51',
    name: 'stacker',
    url: 'https://play.famobi.com/square-stacker',
    images: 'https://i.ibb.co/s6Pn0d1/Square-Stacker-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g51',
  },
  {
    id: '52',
    name: '7 words',
    url: 'https://play.famobi.com/7-words',
    images: 'https://i.ibb.co/vx8gZfk/7-Words-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g52',
  },
  {
    id: '53',
    name: 'Alien',
    url: 'https://play.famobi.com/alien-quest',
    images: 'https://i.ibb.co/cJ8RHLx/Alien-Quest-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g53',
  },
  {
    id: '54',
    name: 'hangman',
    url: 'https://play.famobi.com/sweet-hangman',
    images: 'https://i.ibb.co/17QsSpr/Sweet-Hangman-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g54',
  },
  {
    id: '55',
    name: 'geo quiz',
    url: 'https://play.famobi.com/geo-quiz-europe',
    images: 'https://i.ibb.co/1z1qDy5/Geo-Quiz-Europe-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g55',
  },
  {
    id: '56',
    name: 'animal',
    url: 'https://play.famobi.com/animal-quiz',
    images: 'https://i.ibb.co/JyfFHB9/Animal-Quiz-Christmas-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g56',
  },
  {
    id: '57',
    name: 'fluffyegg',
    url: 'https://play.famobi.com/fluffy-egg',
    images: 'https://i.ibb.co/hYZnjGH/Fluffy-Egg-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g57',
  },
  {
    id: '58',
    name: 'wordguess4',
    url: 'https://play.famobi.com/wordguess-4images',
    images: 'https://i.ibb.co/FsMZ4jH/Wordguess4-Images-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g58',
  },
  {
    id: '59',
    name: 'Cat',
    url: 'https://play.famobi.com/what-famous-cat-are-you',
    images: 'https://i.ibb.co/qMJKgDG/What-Famous-Cat-Are-You-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g59',
  },
  {
    id: '60',
    name: 'wordheavy',
    url: 'https://play.famobi.com/wordguess-2-heavy',
    images: 'https://i.ibb.co/T2ysjG6/Wordguess2-Heavy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g60',
  },
  {
    id: '61',
    name: 'wordguess',
    url: 'https://play.famobi.com/wordguess-2-easy',
    images: 'https://i.ibb.co/bWH048T/Wordguess2-Easy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g61',
  },
  {
    id: '62',
    name: 'crossover',
    url: 'https://play.famobi.com/crossover-21',
    images: 'https://i.ibb.co/grKLbMR/Crossover21-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g62',
  },
  {
    id: '63',
    name: 'pirate',
    url: 'https://play.famobi.com/pirate-cards',
    images: 'https://i.ibb.co/3TFMmbW/Pirate-Cards-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g63',
  },
  {
    id: '64',
    name: 'legend',
    url: 'https://play.famobi.com/solitaire-legend',
    images: 'https://i.ibb.co/CzzqBP0/Solitaire-Legend-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g64',
  },
  {
    id: '65',
    name: 'solitaire',
    url: 'https://play.famobi.com/solitaire-classic-christmas',
    images: 'https://i.ibb.co/vcgsNgG/Solitaire-Classic-Christmas-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g65',
  },
  {
    id: '66',
    name: 'mafia poker',
    url: 'https://play.famobi.com/mafia-poker',
    images: 'https://i.ibb.co/Mhd66fM/Mafia-Poker-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g66',
  },
  {
    id: '67',
    name: 'matchcard',
    url: 'https://play.famobi.com/matching-card-heroes',
    images: 'https://i.ibb.co/YQ4vtFz/Matching-Card-Heroes-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g67',
  },
  {
    id: '68',
    name: 'kitten',
    url: 'https://play.famobi.com/kitten-match',
    images: 'https://i.ibb.co/DY17cdJ/Kitten-Match-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g68',
  },
  {
    id: '69',
    name: 'rummy',
    url: 'https://play.famobi.com/gin-rummy-plus',
    images: 'https://i.ibb.co/d0dX2bx/Gin-Rummy-Plus-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g69',
  },
  {
    id: '70',
    name: 'solitaire',
    url: 'https://play.famobi.com/3d-solitaire',
    images: 'https://i.ibb.co/3021Rcn/3d-Solitaire-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g70',
  },
  {
    id: '71',
    name: 'cards',
    url: 'https://play.famobi.com/duo-cards',
    images: 'https://i.ibb.co/RcGzQpd/Duo-Cards-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g71',
  },
  {
    id: '72',
    name: 'blackjack',
    url: 'https://play.famobi.com/blackjack-bet',
    images: 'https://i.ibb.co/Kj685fh/Black-Jack-Bet-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g72',
  },
  {
    id: '73',
    name: 'klondike',
    url: 'https://play.famobi.com/solitaire-klondike',
    images: 'https://i.ibb.co/W3PzpPr/Solitaire-Klondike-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g73',
  },
  {
    id: '74',
    name: 'freecell',
    url: 'https://play.famobi.com/freecell-solitaire-classic',
    images: 'https://i.ibb.co/Y2hmT5k/Free-Cell-Solitaire-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g74',
  },
  {
    id: '75',
    name: 'tri peak',
    url: 'https://play.famobi.com/monkey-bounce',
    images: 'https://i.ibb.co/jZSjxWv/Tri-Peaks-Solitaire-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g75',
  },
  {
    id: '76',
    name: 'kk tri',
    url: 'https://play.famobi.com/kk-tri-towers-solitaire',
    images: 'https://i.ibb.co/ZzD0qHq/Kk-Tri-Towers-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g76',
  },
  {
    id: '77',
    name: 'spider',
    url: 'https://play.famobi.com/spider-solitaire-classic',
    images: 'https://i.ibb.co/fq2YFBK/Spider-Solitaire-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g77',
  },
  {
    id: '78',
    name: 'classic',
    url: 'https://play.famobi.com/western-solitaire',
    images: 'https://i.ibb.co/NjbsN86/Western-Solitaire-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g78',
  },
  {
    id: '79',
    name: 'solitaire-master',
    url: 'https://play.famobi.com/solitaire-master',
    images: 'https://i.ibb.co/SB77sdr/Solitaire-Master-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g79',
  },
  {
    id: '80',
    name: 'solitaire',
    url: 'https://play.famobi.com/solitaire-classic-easter',
    images: 'https://i.ibb.co/2Skz3mM/Solitaire-Classic-Easter-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g80',
  },
  {
    id: '81',
    name: 'Surgery',
    url: 'https://play.famobi.com/emergency-surgery',
    images: 'https://i.ibb.co/Prp5C6v/Emergency-Surgery-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g81',
  },
  {
    id: '82',
    name: 'kawaii',
    url: 'https://play.famobi.com/kawaii-chibi-creator',
    images: 'https://i.ibb.co/Hz1d1bG/Kawaii-Chibi-Creator-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g82',
  },
  {
    id: '83',
    name: 'lily birthday',
    url: 'https://play.famobi.com/baby-lily-birthday',
    images: 'https://i.ibb.co/Vm0S3QH/Baby-Lily-Birthday-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g83',
  },
  {
    id: '84',
    name: 'pie',
    url: 'https://play.famobi.com/pie-realife-cooking',
    images: 'https://i.ibb.co/mcRkmLm/Pie-Realife-Cooking-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g84',
  },
  {
    id: '85',
    name: 'baby lily',
    url: 'https://play.famobi.com/baby-lily-care',
    images: 'https://i.ibb.co/rMc1RB2/Baby-Lily-Care-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g85',
  },
  {
    id: '86',
    name: 'baby lily',
    url: 'https://play.famobi.com/baby-lily-sick-day',
    images: 'https://i.ibb.co/m48yfCM/Baby-Lily-Sick-Day-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g86',
  },
  {
    id: '87',
    name: 'deer',
    url: 'https://play.famobi.com/my-fairytale-deer',
    images: 'https://i.ibb.co/qRbLYCS/My-Fairytale-Deer-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g87',
  },
  {
    id: '88',
    name: 'waterhorse',
    url: 'https://play.famobi.com/my-fairytale-water-horse',
    images: 'https://i.ibb.co/DMFnttS/My-Fairytale-Water-Horse-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g88',
  },
  {
    id: '89',
    name: 'panda',
    url: 'https://play.famobi.com/happy-panda',
    images: 'https://i.ibb.co/HzP1jCX/Happy-Panda-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g89',
  },
  {
    id: '90',
    name: 'koala',
    url: 'https://play.famobi.com/happy-koala',
    images: 'https://i.ibb.co/5sZpTfV/Happy-Koala-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g90',
  },
  {
    id: '91',
    name: 'sailorgirls',
    url: 'https://play.famobi.com/sailor-girls-avatar-maker',
    images: 'https://i.ibb.co/R3TZc32/Sailor-Girls-Avatar-Maker-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g91',
  },
  {
    id: '92',
    name: 'animefantasy',
    url: 'https://play.famobi.com/3d-anime-fantasy',
    images: 'https://i.ibb.co/FHS12qQ/3d-Anime-Fantasy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g92',
  },
  {
    id: '93',
    name: 'unicorncare',
    url: 'https://play.famobi.com/cute-unicorn-care',
    images: 'https://i.ibb.co/bHMw4QP/Cute-Unicorn-Care-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g93',
  },
  {
    id: '94',
    name: 'fairytale',
    url: 'https://play.famobi.com/my-fairytale-tiger',
    images: 'https://i.ibb.co/jVjF9LG/My-Fairytale-Tiger-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g94',
  },
  {
    id: '95',
    name: 'lemur',
    url: 'https://play.famobi.com/happy-lemur',
    images: 'https://i.ibb.co/y5wLdkH/Happy-Lemur-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g95',
  },
  {
    id: '96',
    name: 'jungle',
    url: 'https://play.famobi.com/jungle-run',
    images: 'https://i.ibb.co/94K1hws/Jungle-Run-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g96',
  },
  {
    id: '97',
    name: 'banana',
    url: 'https://play.famobi.com/banana-run',
    images: 'https://i.ibb.co/KKTLd20/Banana-Run-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g97',
  },
  {
    id: '98',
    name: 'outcome',
    url: 'https://play.famobi.com/outcome',
    images: 'https://i.ibb.co/5BnSYvL/Outcome-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g98',
  },
  {
    id: '99',
    name: 'yeti-sensa',
    url: 'https://play.famobi.com/yeti-sensation',
    images: 'https://i.ibb.co/3pRP2Xt/Yeti-Sensation-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g99',
  },
  {
    id: '100',
    name: 'greedy',
    url: 'https://play.famobi.com/greedy-rabbit',
    images: 'https://i.ibb.co/V3fmYkM/Greedy-Rabbit-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g100',
  },
  {
    id: '101',
    name: 'snowball',
    url: 'https://play.famobi.com/snowball-christmas-world',
    images: 'https://i.ibb.co/bQtkZn0/Snowball-Christmas-World-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g101',
  },
  {
    id: '102',
    name: 'basket-ball',
    url: 'https://play.famobi.com/basket-and-ball',
    images: 'https://i.ibb.co/KyPyryH/Basket-And-Ball-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g102',
  },
  {
    id: '103',
    name: 'snowball',
    url: 'https://play.famobi.com/snowball-world',
    images: 'https://i.ibb.co/f1NbQyG/Snowball-World-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g103',
  },
  {
    id: '104',
    name: 'key-shield',
    url: 'https://play.famobi.com/key-and-shield',
    images: 'https://i.ibb.co/v4Lp3db/Key-And-Shield-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g104',
  },
  {
    id: '105',
    name: 'jack',
    url: 'https://play.famobi.com/running-jack',
    images: 'https://i.ibb.co/yygGhcj/Running-Jack-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g105',
  },
  {
    id: '106',
    name: 'goldblade',
    url: 'https://play.famobi.com/princess-goldblade',
    images: 'https://i.ibb.co/KK33Q1J/Princess-Goldblade-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g106',
  },
  {
    id: '107',
    name: 'monster',
    url: 'https://play.famobi.com/sweets-monster',
    images: 'https://i.ibb.co/VwTL27G/Sweets-Monster-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g107',
  },
  {
    id: '108',
    name: 'the green',
    url: 'https://play.famobi.com/the-green-mission',
    images: 'https://i.ibb.co/gwfYthb/The-Green-Mission-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g108',
  },
  {
    id: '109',
    name: 'nut rush 3',
    url: 'https://play.famobi.com/nut-rush3',
    images: 'https://i.ibb.co/277WkWp/Nut-Rush3-Christmas-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g109',
  },
  {
    id: '110',
    name: 'red head',
    url: 'https://play.famobi.com/red-head',
    images: 'https://i.ibb.co/V3JT8KJ/Red-Head-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g110',
  },
  {
    id: '111',
    name: 'kk shadow',
    url: 'https://play.famobi.com/kk-shadow-run',
    images: 'https://i.ibb.co/2ZHqngM/Kiba-Kumba-Shadow-Run-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g111',
  },
  {
    id: '112',
    name: 'highjump',
    url: 'https://play.famobi.com/highjump',
    images: 'https://i.ibb.co/VSRMxmT/High-Jump-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g112',
  },
  {
    id: '113',
    name: 'kk jungle',
    url: 'https://play.famobi.com/kk-jungle-chaos',
    images: 'https://i.ibb.co/z7mTdMd/Jungle-Chaos-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g113',
  },
  {
    id: '114',
    name: 'ufo run',
    url: 'https://play.famobi.com/ufo-run',
    images: 'https://i.ibb.co/sQgrqV1/Ufo-Run-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g114',
  },
  {
    id: '115',
    name: 'nut rush2',
    url: 'https://play.famobi.com/nut-rush2',
    images: 'https://i.ibb.co/RDZHvKX/Nut-Rush2-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g115',
  },
  {
    id: '116',
    name: 'pull pins',
    url: 'https://play.famobi.com/pull-pins',
    images: 'https://i.ibb.co/37kfGY5/Pull-Pins-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g116',
  },
  {
    id: '117',
    name: 'bubble tower',
    url: 'https://play.famobi.com/bubble-tower-3d',
    images: 'https://i.ibb.co/WKZ0Y5M/Bubble-Tower3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g117',
  },
  {
    id: '118',
    name: 'bus parking',
    url: 'https://play.famobi.com/bus-parking-3d',
    images: 'https://i.ibb.co/M16fMRd/Bus-Parking3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g118',
  },
  {
    id: '119',
    name: 'crazy caves',
    url: 'https://play.famobi.com/crazy-caves',
    images: 'https://i.ibb.co/Cn5FZVd/Crazy-Caves-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g119',
  },
  {
    id: '120',
    name: 'hoop royale',
    url: 'https://play.famobi.com/hoop-royale',
    images: 'https://i.ibb.co/wCmXwJG/Hoop-Royale-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g120',
  },
  {
    id: '121',
    name: 'tnt bomb',
    url: 'https://play.famobi.com/tnt-bomb',
    images: 'https://i.ibb.co/c2ST7P6/Tnt-Bomb-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g121',
  },
  {
    id: '122',
    name: 'stack smash',
    url: 'https://play.famobi.com/stack-smash',
    images: 'https://i.ibb.co/XttxFwM/Stack-Smash-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g122',
  },
  {
    id: '123',
    name: 'monkey bounce',
    url: 'https://play.famobi.com/monkey-bounce',
    images: 'https://i.ibb.co/mDZg73t/Monkey-Bounce-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g123',
  },
  {
    id: '124',
    name: 'curve ball',
    url: 'https://play.famobi.com/curve-ball-3d',
    images: 'https://i.ibb.co/dW4K13r/Curve-Ball3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g124',
  },
  {
    id: '125',
    name: 'slice rush',
    url: 'https://play.famobi.com/slice-rush',
    images: 'https://i.ibb.co/BjB926t/Slice-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g125',
  },
  {
    id: '126',
    name: 'hippo pizza',
    url: 'https://play.famobi.com/hippo-pizza-chef',
    images: 'https://i.ibb.co/rthXWr9/Hippo-Pizza-Chef-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g126',
  },
  {
    id: '127',
    name: 'domino frenzy',
    url: 'https://play.famobi.com/domino-frenzy',
    images: 'https://i.ibb.co/xgMp5Jj/Domino-Frenzy-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g127',
  },
  {
    id: '128',
    name: 'cannon balls',
    url: 'https://play.famobi.com/cannon-balls-3d',
    images: 'https://i.ibb.co/xsT3H15/Cannon-Balls3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g128',
  },
  {
    id: '129',
    name: 'pets rush',
    url: 'https://play.famobi.com/pets-rush',
    images: 'https://i.ibb.co/9yLT7WF/Pets-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g129',
  },
  {
    id: '130',
    name: 'zoo feeder',
    url: 'https://play.famobi.com/zoo-feeder',
    images: 'https://i.ibb.co/8YMLdqX/Zoo-Feeder-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g130',
  },
  {
    id: '131',
    name: 'element balls',
    url: 'https://play.famobi.com/element-balls',
    images: 'https://i.ibb.co/mXnFfSS/Element-Balls-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g131',
  },
  {
    id: '132',
    name: 'tower crash',
    url: 'https://play.famobi.com/tower-crash-3d',
    images: 'https://i.ibb.co/wQgGdR7/Tower-Crash3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g132',
  },
  {
    id: '133',
    name: 'sushi roll',
    url: 'https://play.famobi.com/sushi-roll',
    images: 'https://i.ibb.co/yhfKL86/Sushi-Roll-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g133',
  },
  {
    id: '134',
    name: 'knife rain',
    url: 'https://play.famobi.com/knife-rain',
    images: 'https://i.ibb.co/F8yb54F/Knife-Rain-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g134',
  },
  {
    id: '135',
    name: 'motoparty',
    url: 'https://play.famobi.com/moto-x3m-pool-party',
    images: 'https://i.ibb.co/sHTsXx6/Moto-X3m-Pool-Party-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g135',
  },
  {
    id: '136',
    name: 'drivers',
    url: 'https://play.famobi.com/adventure-drivers',
    images: 'https://i.ibb.co/KLM0vk9/Adventure-Drivers-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g136',
  },
  {
    id: '137',
    name: 'moto x3m',
    url: 'https://play.famobi.com/moto-x3m',
    images: 'https://i.ibb.co/LC6RLW9/Moto-X3m-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g137',
  },
  {
    id: '138',
    name: 'high hills',
    url: 'https://play.famobi.com/high-hills',
    images: 'https://i.ibb.co/gJVcJPD/High-Hills-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g138',
  },
  {
    id: '139',
    name: 'drag racing',
    url: 'https://play.famobi.com/drag-racing-club',
    images: 'https://i.ibb.co/GpmZ9PJ/Drag-Racing-Club-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g139',
  },
  {
    id: '140',
    name: 'race right',
    url: 'https://play.famobi.com/race-right',
    images: 'https://i.ibb.co/rd0p4Gp/Race-Right-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g140',
  },
  {
    id: '141',
    name: 'biker street',
    url: 'https://play.famobi.com/biker-street',
    images: 'https://i.ibb.co/PFTLfgr/Biker-Street-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g141',
  },
  {
    id: '142',
    name: 'highway rider',
    url: 'https://play.famobi.com/highway-rider-extreme',
    images: 'https://i.ibb.co/rQPCKTr/Highway-Rider-Extreme-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g142',
  },
  {
    id: '143',
    name: 'moto fury',
    url: 'https://play.famobi.com/moto-fury',
    images: 'https://i.ibb.co/BsxmygR/Moto-Fury-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g143',
  },
  {
    id: '144',
    name: 'drift cup',
    url: 'https://play.famobi.com/drift-cup-racing',
    images: 'https://i.ibb.co/pQKhHfk/Drift-Cup-Racing-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g144',
  },
  {
    id: '145',
    name: 'trucks',
    url: 'https://play.famobi.com/racing-monster-trucks',
    images: 'https://i.ibb.co/dWjMXWX/Racing-Monster-Trucks-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g145',
  },
  {
    id: '146',
    name: 'cars',
    url: 'https://play.famobi.com/racing-cars',
    images: 'https://i.ibb.co/56ydfyD/Racing-Cars-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g146',
  },
  {
    id: '147',
    name: 'truck trials',
    url: 'https://play.famobi.com/truck-trials',
    images: 'https://i.ibb.co/NND1vLJ/Truck-Trials-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g147',
  },
  {
    id: '148',
    name: 'thug racer',
    url: 'https://play.famobi.com/thug-racer',
    images: 'https://i.ibb.co/12GHSvJ/Thug-Racer-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g148',
  },
  {
    id: '149',
    name: 'truck',
    url: 'https://play.famobi.com/endless-truck',
    images: 'https://i.ibb.co/ZJn8ZCT/Endless-Truck-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g149',
  },
  {
    id: '150',
    name: 'rival rush',
    url: 'https://play.famobi.com/rival-rush',
    images: 'https://i.ibb.co/kqM0YVc/Rival-Rush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g150',
  },
  {
    id: '151',
    name: 'street',
    url: 'https://play.famobi.com/street-pursuit',
    images: 'https://i.ibb.co/QKg3NkS/Street-Pursuit-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g151',
  },
  {
    id: '152',
    name: 'streetrace',
    url: 'https://play.famobi.com/streetrace-fury',
    images: 'https://i.ibb.co/WkPDv9b/Street-Race-Fury-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g152',
  },
  {
    id: '153',
    name: '2 cars',
    url: 'https://play.famobi.com/2cars',
    images: 'https://i.ibb.co/MCS8R7X/2-Cars-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g153',
  },
  {
    id: '154',
    name: 'drag racing',
    url: 'https://play.famobi.com/drag-racing-club',
    images: 'https://i.ibb.co/GpmZ9PJ/Drag-Racing-Club-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g154',
  },
  {
    id: '155',
    name: 'basketball',
    url: 'https://play.famobi.com/3d-basketball',
    images: 'https://i.ibb.co/DgzTxj1/3d-Basketball-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g155',
  },
  {
    id: '156',
    name: 'darts',
    url: 'https://play.famobi.com/3d-darts',
    images: 'https://i.ibb.co/6yNqr6P/3d-Darts-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g156',
  },
  {
    id: '157',
    name: 'dunk brush',
    url: 'https://play.famobi.com/dunk-brush',
    images: 'https://i.ibb.co/NY0smbG/Dunk-Brush-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g157',
  },
  {
    id: '158',
    name: 'goalkeeper',
    url: 'https://play.famobi.com/goalkeeper-champ',
    images: 'https://i.ibb.co/nLZYp6c/Goalkeeper-Champ-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g158',
  },
  {
    id: '159',
    name: 'blaze kick',
    url: 'https://play.famobi.com/blaze-kick',
    images: 'https://i.ibb.co/5ssTTvy/Blaze-Kick-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g159',
  },
  {
    id: '160',
    name: 'cheap golf',
    url: 'https://play.famobi.com/cheap-golf',
    images: 'https://i.ibb.co/qg6CT78/Cheap-Golf-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g160',
  },
  {
    id: '161',
    name: 'free kick',
    url: 'https://play.famobi.com/3d-free-kick-world-cup-18',
    images: 'https://i.ibb.co/5YQvqRV/3d-Free-Kick-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g161',
  },
  {
    id: '162',
    name: 'air hockey',
    url: 'https://play.famobi.com/3d-air-hockey',
    images: 'https://i.ibb.co/yVghVjJ/3d-Air-Hockey-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g162',
  },
  {
    id: '163',
    name: 'soccer',
    url: 'https://play.famobi.com/soccer-champ-2018',
    images: 'https://i.ibb.co/1fgJwNt/Soccer-Champ2018-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g163',
  },
  {
    id: '164',
    name: '3d bowling',
    url: 'https://play.famobi.com/3d-bowling',
    images: 'https://i.ibb.co/KNx2bj1/3d-Bowling-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g164',
  },
  {
    id: '165',
    name: 'free kick',
    url: 'https://play.famobi.com/3d-free-kick',
    images: 'https://i.ibb.co/tJTRtPD/3d-Free-Kick-World-Cup18-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g165',
  },
  {
    id: '166',
    name: 'soccercup',
    url: 'https://play.famobi.com/soccertastic-world-cup-18',
    images: 'https://i.ibb.co/YpTm4bf/Soccertastic-World-Cup18-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g166',
  },
  {
    id: '167',
    name: 'penality',
    url: 'https://play.famobi.com/world-cup-penalty-2018',
    images: 'https://i.ibb.co/F4FBsgp/World-Cup-Penalty-2018-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g167',
  },
  {
    id: '168',
    name: 'billiards',
    url: 'https://play.famobi.com/8-ball-billiards-classic',
    images: 'https://i.ibb.co/qFSFNmv/8-Ball-Billiards-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g168',
  },
  {
    id: '169',
    name: 'archery',
    url: 'https://play.famobi.com/archery-world-tour',
    images: 'https://i.ibb.co/VTK2SJr/Archery-World-Tour-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g169',
  },
  {
    id: '170',
    name: 'street hoops',
    url: 'https://play.famobi.com/street-hoops-3d',
    images: 'https://i.ibb.co/R6nWj8c/Street-Hoops3d-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g170',
  },
  {
    id: '171',
    name: 'slam dunk',
    url: 'https://play.famobi.com/slam-dunk-basketball',
    images: 'https://i.ibb.co/SBF12Sw/Slam-Dunk-Basketball-Teaser-B.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g171',
  },
  {
    id: '172',
    name: 'moto fury',
    url: 'https://play.famobi.com/moto-fury',
    images: 'https://i.ibb.co/BsxmygR/Moto-Fury-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g172',
  },
  {
    id: '173',
    name: 'perfect piano',
    url: 'https://play.famobi.com/perfect-piano',
    images: 'https://i.ibb.co/hCykXk7/Perfect-Piano-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g173',
  },
  {
    id: '174',
    name: 'TT',
    url: 'https://play.famobi.com/table-tennis-world-tour',
    images: 'https://i.ibb.co/McMZgBs/Table-Tennis-World-Tour-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g174',
  },
  {
    id: '175',
    name: 'onet connect',
    url: 'https://play.famobi.com/onet-connect-classic',
    images: 'https://i.ibb.co/PMKqVFH/Onet-Connect-Classic-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g175',
  },
  {
    id: '176',
    name: 'candy bubble',
    url: 'https://play.famobi.com/candy-bubble',
    images: 'https://i.ibb.co/k3P9H6g/Candy-Bubble-Teaser.jpg',
    bgcolor: '#232F3E',
    type: 'game',
    uuid: 'g176',
  },
];

export {
  NewGames,
  BestGames,
  Match3Games,
  BubbleGames,
  PuzzleGames,
  QuizGames,
  CardGames,
  GirlGames,
  JumpGames,
  ArcadeGames,
  RacingGames,
  SportsGames,
  AllGames,
};
